
//                              !! RAM !!

package puexamroutine.ui.form;

import java.awt.HeadlessException;
import puexamroutine.ui.form.editors.*;
import puexamroutine.control.domain.*;

/**
 *
 * @author  Sumit Shresth
 */
public class BackCandidatesForm extends javax.swing.JDialog {
    /** A return status code - returned if Cancel button has been pressed */
    public static final int RET_CANCEL = 0;
    /** A return status code - returned if OK button has been pressed */
    public static final int RET_OK = 1;
    
    /** Creates new form BackCandidatesForm */
    public BackCandidatesForm(java.awt.Frame parent, String Program, String College ) {
        super(parent, true );
        this.Program = Program;
        this.College = College;
        this.BackCoursesEditor = new BackCoursesEditor();   
        this.BackCandidateSemesterEditor = new BackCandidateSemesterEditor();
        initComponents();        
        this.PrgCombo.addItem( Program );
        this.CollegeCombo.addItem( College );        
        this.model = (javax.swing.table.DefaultTableModel) this.Table.getModel();
        this.setLocationRelativeTo( null );
    }
    
    public BackCandidatesForm(java.awt.Frame parent, String Program, String College, java.util.Map<CourseCode,String> selectCourses ) {
        this( parent, Program, College );
        this.BackCoursesEditor.setSelectCourses(selectCourses);
    }
    
    /** @return the return status of this dialog - one of RET_OK or RET_CANCEL */
    public int getReturnStatus() {
        return returnStatus;
    }

    private void addRow() {
        if (this.isFilled()) {
            Object[] data = {"", ""};
            this.model.addRow(data);
            this.BackCoursesEditor.onRowAddition( null );
        }
    }

    private boolean delRow() throws HeadlessException {
        int index = this.Table.getSelectedRow();
        if (index < 0) {
            javax.swing.JOptionPane.showMessageDialog(null, "Please select the candidate to be deleted", "Row not Selected", javax.swing.JOptionPane.ERROR_MESSAGE);
            return true;
        }
        this.model.removeRow(index);
        this.BackCoursesEditor.onRowDeleted(index);        
        this.BackCandidateSemesterEditor.onRowDeleted(index);
        return false;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        CollegeCombo = new javax.swing.JComboBox();
        PrgCombo = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSplitPane1 = new javax.swing.JSplitPane();
        WestPanel = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        EastPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();

        setTitle("BackCandidates Form");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("College");

        jLabel2.setText("Program");

        jButton1.setText("Add");
        jButton1.setToolTipText("add Back Candidate");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Del");
        jButton2.setToolTipText("delete selected candidate");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout WestPanelLayout = new javax.swing.GroupLayout(WestPanel);
        WestPanel.setLayout(WestPanelLayout);
        WestPanelLayout.setHorizontalGroup(
            WestPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton1)
            .addComponent(jButton2)
        );
        WestPanelLayout.setVerticalGroup(
            WestPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WestPanelLayout.createSequentialGroup()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap(227, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(WestPanel);

        EastPanel.setLayout(new java.awt.BorderLayout());

        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Candidate ID", "Semester", "Back Courses"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Integer.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        Table.getTableHeader().setReorderingAllowed(false);
        Table.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TableKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(Table);
        Table.getColumnModel().getColumn(1).setCellEditor(BackCandidateSemesterEditor);
        Table.getColumnModel().getColumn(2).setCellEditor(BackCoursesEditor);

        EastPanel.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jSplitPane1.setRightComponent(EastPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CollegeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(PrgCombo, 0, 237, Short.MAX_VALUE))
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 565, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancelButton))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cancelButton, okButton});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(CollegeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(PrgCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton)
                    .addComponent(okButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        doClose(RET_OK);
    }//GEN-LAST:event_okButtonActionPerformed
    
    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        doClose(RET_CANCEL);
    }//GEN-LAST:event_cancelButtonActionPerformed
    
    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        doClose(RET_CANCEL);
    }//GEN-LAST:event_closeDialog

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        addRow();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (delRow()) {
            return;
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void TableKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TableKeyPressed
        final int DOWN_KEY = 40;
        if( evt.getKeyChar() == java.awt.event.KeyEvent.VK_DELETE ){
            this.delRow();
            return;
        }
        if( this.Table.getSelectedRow() < this.Table.getModel().getRowCount() - 1 ){            
            return;
        }
        if( evt.getKeyCode() == DOWN_KEY ){
            this.addRow();
        }   
}//GEN-LAST:event_TableKeyPressed
    
    private void doClose(int retStatus) {
        returnStatus = retStatus;
        setVisible(false);
        dispose();
    }
    
    private boolean isFilled(){
        return this.Table.getRowCount()<1 || !this.Table.getValueAt( this.Table.getRowCount()-1, 0 ).equals("");
    }
    
    public CollegeBackCandidates getBackCandidates(){
        CollegeBackCandidates Candidates = new CollegeBackCandidates( new College( this.CollegeCombo.getSelectedItem().toString() ), new Program (this.PrgCombo.getSelectedItem().toString()) );
        java.util.List<BackCandidateForm> formList = this.BackCoursesEditor.getForms();
        for( int i=0; i<formList.size(); i++){
            BackCandidateForm form = formList.get(i);
            int sem = Integer.parseInt( this.Table.getValueAt(i, 1 ).toString() );
            Candidate cand = new Candidate( this.Table.getValueAt(i, 0 ).toString(), Candidates.getProgram(), Candidates.getCollege() , sem ,(sem==Candidate.NON_REGULAR)?puexamroutine.control.domain.interfaces.CandidateInterface.BACK_ONLY:Candidate.REGULAR_WITH_BACK );
            cand.addBackPapers( java.util.Arrays.asList(form.getCourses()) );
            Candidates.addBackPaperCandidate(cand);
            System.out.println("This is sem of "+cand.getCandidateID()+" "+sem);
        }
        return Candidates;        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox CollegeCombo;
    private javax.swing.JPanel EastPanel;
    private javax.swing.JComboBox PrgCombo;
    private javax.swing.JTable Table;
    private javax.swing.JPanel WestPanel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JButton okButton;
    // End of variables declaration//GEN-END:variables
    
    private int returnStatus = RET_CANCEL;
    private BackCoursesEditor BackCoursesEditor;
    private BackCandidateSemesterEditor BackCandidateSemesterEditor;
    private javax.swing.table.DefaultTableModel model;
    private String College, Program;
}