
//                          !! RAM !!

package puexamroutine.ui.form;

import java.awt.HeadlessException;
import java.util.*;
import puexamroutine.control.domain.CourseCode;
import puexamroutine.control.domain.Candidate;
import puexamroutine.ui.form.editors.CourseCodeEditor;

/**
 *
 * @author  Sumit Shresth
 */
public class BackCandidateForm extends javax.swing.JDialog {
    /** A return status code - returned if Cancel button has been pressed */
    public static final int RET_CANCEL = 0;
    /** A return status code - returned if OK button has been pressed */
    public static final int RET_OK = 1;
    
    /** Creates new form BackCandidateForm */
    public BackCandidateForm(java.awt.Frame parent, final String ID ) {
        super( parent, true );                
        initComponents();
        this.model = (javax.swing.table.DefaultTableModel) this.Table.getModel();
        this.setCandidateID(ID);
        this.setLocationRelativeTo( null );
        this.addBtn.requestFocusInWindow();
    }
    
    public BackCandidateForm(java.awt.Frame parent, final String ID, final java.util.Map<CourseCode,String> grpCourses ) {
        this( parent, ID );
        try{
            this.CourseEditor.addSelectCourses(grpCourses);            
        }
        catch( Exception e ){
            this.ERROR_MESSAGE = e.getMessage();
        }
    }
    
    public BackCandidateForm(java.awt.Frame parent, final Candidate ID, final java.util.Map<CourseCode,String> grpCourses ) {
        this( parent, ID.getCandidateID(), grpCourses );
        java.util.List<CourseCode> BkCourses = (java.util.List)ID.getBackCourses();
        this.CourseEditor.addCourses( BkCourses );
        java.util.Iterator<CourseCode> BkCourseItr = BkCourses.iterator();
        while( BkCourseItr.hasNext() ){
            this.model.addRow(new Object[]{BkCourseItr.next()} );            
        }
    }
    
    /** @return the return status of this dialog - one of RET_OK or RET_CANCEL */
    public int getReturnStatus() {
        return returnStatus;
    }

    private boolean addRow() {
        if( this.ERROR_MESSAGE != null ){
            javax.swing.JOptionPane.showMessageDialog(null, this.ERROR_MESSAGE, "Course Code Not present", javax.swing.JOptionPane.ERROR_MESSAGE);
            return true;
        }
        
        if (!this.isfilled()) {
            return true;
        }
        
        this.model.addRow(new String[]{""});
        return false;
    }

    private void delRow() throws HeadlessException {
        int i = this.Table.getSelectedRow();
        if (i > -1) {
            this.CourseEditor.onRowDeleted(i);
            this.model.removeRow(i);            
        } else {
            javax.swing.JOptionPane.showMessageDialog(null, "Please select the course to be deleted", "Row not selected", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSplitPane1 = new javax.swing.JSplitPane();
        WestPanel = new javax.swing.JPanel();
        addBtn = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        EastPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        cand = new javax.swing.JComboBox();

        setTitle("Back Candidate Form");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Candidate ID");

        addBtn.setText("Add");
        addBtn.setNextFocusableComponent(Table);
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        jButton2.setText("Del");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout WestPanelLayout = new javax.swing.GroupLayout(WestPanel);
        WestPanel.setLayout(WestPanelLayout);
        WestPanelLayout.setHorizontalGroup(
            WestPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(addBtn)
            .addComponent(jButton2)
        );
        WestPanelLayout.setVerticalGroup(
            WestPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WestPanelLayout.createSequentialGroup()
                .addComponent(addBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap(98, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(WestPanel);

        EastPanel.setLayout(new java.awt.BorderLayout());

        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Back Courses"
            }
        ));
        Table.getTableHeader().setReorderingAllowed(false);
        Table.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TableKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(Table);
        Table.getColumnModel().getColumn(0).setCellEditor(this.CourseEditor);

        EastPanel.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jSplitPane1.setRightComponent(EastPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cand, 0, 159, Short.MAX_VALUE)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cancelButton, okButton});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton)
                    .addComponent(okButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        doClose(RET_OK);
    }//GEN-LAST:event_okButtonActionPerformed
    
    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        doClose(RET_CANCEL);
    }//GEN-LAST:event_cancelButtonActionPerformed
    
    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        doClose(RET_CANCEL);
    }//GEN-LAST:event_closeDialog

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        if (addRow()) {
            return;
}//GEN-LAST:event_addBtnActionPerformed
    }                                        

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        delRow();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void TableKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TableKeyPressed
        final int DOWN_KEY = 40;
        if( evt.getKeyChar() == java.awt.event.KeyEvent.VK_DELETE ){
            this.delRow();
            return;
        }
        if( this.Table.getSelectedRow() < this.Table.getModel().getRowCount() - 1 ){            
            return;
        }
        if( evt.getKeyCode() == DOWN_KEY ){
            this.addRow();            
        }           
        
        this.Table.requestFocusInWindow();
}//GEN-LAST:event_TableKeyPressed
    
    private void doClose(int retStatus) {
        returnStatus = retStatus;
        setVisible(false);
        dispose();
    }
        
    public CourseCode[] getCourses(){
        try{
            List<CourseCode> list = this.CourseEditor.getForms();            
            return list.toArray( new CourseCode[]{} );
        }
        catch( Exception e ){
            return null;
        }
    }
    
    private boolean isfilled(){
        return this.model.getRowCount() < 1 || !this.model.getValueAt( this.model.getRowCount()-1, 0 ).equals("");
    }
    
    public void setCandidateID( String ID ){
        this.ID = ID;
        int selectindx = this.cand.getSelectedIndex();
        if( selectindx >= 0 )
            this.cand.removeItemAt( selectindx );
        this.cand.addItem( ID );
    }
    
    public final String getCandidateID(){
        return this.cand.getSelectedItem().toString();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel EastPanel;
    private javax.swing.JTable Table;
    private javax.swing.JPanel WestPanel;
    private javax.swing.JButton addBtn;
    private javax.swing.JButton cancelButton;
    private javax.swing.JComboBox cand;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JButton okButton;
    // End of variables declaration//GEN-END:variables
    
    private int returnStatus = RET_CANCEL;
    private javax.swing.table.DefaultTableModel model;    
    private String ID;
    private CourseCodeEditor CourseEditor = new CourseCodeEditor();    
    private String ERROR_MESSAGE = null;
}