
//                              !! RAM !!

package puexamroutine.ui.form;

/**
 *
 * @author  sumit shresth
 */
public class BackCanidateSemesterForm extends javax.swing.JDialog {

    public static final int ok = 1, cancel=2;
    
    /** Creates new form BackCanidateSemesterForm */
    public BackCanidateSemesterForm(java.awt.Frame parent) {
        super(parent, true);
        initComponents();        
        this.setLocationRelativeTo( null );
    }
    
    public void initialize( final String Bk, final int sem ){
//        System.out.println( "this is previous sem "+sem + " of "+Bk );
        this.SemText.setText( sem+"" );
        this.backCand.setText(Bk);
        this.prev_sem = sem;
        this.passout.setSelected( sem == puexamroutine.control.domain.Candidate.NON_REGULAR );
        this.onPassoutChange();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        backCand = new javax.swing.JTextField();
        passout = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        SemText = new javax.swing.JFormattedTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Back Candidate Semester Form");

        jLabel1.setText("Canididate Name");

        backCand.setEditable(false);

        passout.setText("Pass Out");
        passout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passoutActionPerformed(evt);
            }
        });

        jLabel2.setText("Semester");

        SemText.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));

        jButton1.setText("Cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("OK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(passout)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SemText, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                            .addComponent(backCand, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(backCand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passout)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(SemText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void passoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passoutActionPerformed
    this.onPassoutChange();
}//GEN-LAST:event_passoutActionPerformed

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    try{
        if(!this.passout.isSelected())this.SemText.commitEdit();
        this.setState(ok);
    }
    catch( Exception e ){
        javax.swing.JOptionPane.showMessageDialog( null, "Semester is not properly filled.\nplease fill properly", "Error", javax.swing.JOptionPane.ERROR_MESSAGE );
    }
}//GEN-LAST:event_jButton2ActionPerformed

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    this.setState( this.cancel );
}//GEN-LAST:event_jButton1ActionPerformed

    private void onPassoutChange(){
        if( this.passout.isSelected() ){
            this.SemText.setValue( null );        
            this.SemText.setEnabled( false );
        }
        else{
            this.SemText.setEnabled( true );
        }
    }

    public void setState( final int s ){
        this.state = s;
        this.setVisible( false );
    }
    
    public final int getState(){
        return this.state;
    }
    
    public final int getSemester(){
        
        if( this.state == this.cancel )
            return this.prev_sem;
        
        if( this.passout.isSelected() )
            return puexamroutine.control.domain.Candidate.NON_REGULAR;
        else
            return Integer.parseInt( this.SemText.getValue().toString() );
    }
    
    public final boolean isRegular(){
        return ! this.passout.isSelected();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField SemText;
    private javax.swing.JTextField backCand;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JCheckBox passout;
    // End of variables declaration//GEN-END:variables

    private int state;
    private int prev_sem;
}