
//                      !! RAM !!

package puexamroutine.ui.form;

import puexamroutine.ui.form.editors.SemesterRegularCourseEditor;
import puexamroutine.ui.form.editors.BackCoursesEditor;
import javax.swing.table.DefaultTableModel;
import puexamroutine.control.domain.*;
import puexamroutine.control.domain.interfaces.CandidateInterface;
import puexamroutine.control.domain.list.SemesterList;
import java.util.Collection;
import java.util.Iterator;

/**
 *
 * @author  Sumit Shresth
 */
public class CollegeForm extends javax.swing.JDialog {
    /** A return status code - returned if Cancel button has been pressed */
    public static final int RET_CANCEL = 0;
    /** A return status code - returned if OK button has been pressed */
    public static final int RET_OK = 1;
    
    /** Creates new form CollegeForm */
    public CollegeForm(java.awt.Frame parent, final String Program, String[] centrelist ) {
        super(parent, true );
        this.BackEditor = new BackCoursesEditor();
        this.RegEditor = new SemesterRegularCourseEditor( Program, null );
        initComponents();
        this.RegTableModel = (DefaultTableModel) this.RegularTable.getModel();
        this.BackTableModel = (DefaultTableModel) this.BackTable.getModel();
        setProgram( Program );
        this.setLocationRelativeTo( null );
        for( int i=0; i<centrelist.length; i++ )
            this.CentreCombo.addItem( centrelist[i] );
    }
    
    public CollegeForm(java.awt.Frame parent, final String Program, String[] centrelist, java.util.Map<CourseCode,String> courses ) {
        this( parent, Program, centrelist );
        this.RegEditor.setSelectCourses(courses);
        this.BackEditor.setSelectCourses(courses);
    }
    
    public CollegeForm(java.awt.Frame parent, final Program Program, final College coll, String[] centrelist, java.util.Map<CourseCode,String> courses ) {
        this( parent, Program.getProgramName(), centrelist, courses );
        this.CollegeText.setText( coll.getCollegeName() );
        java.util.List<RegularCourses> regs = coll.getRegularCourse(Program);
        java.util.List<CandidateInterface> cands = java.util.Arrays.asList( coll.getBackCandidates(Program).getBackPaperCandidates().toArray(new CandidateInterface[]{} ) );
        
        this.RegEditor.addRegularSemesters( regs );
        this.BackEditor.addBackCandidates(cands);
        
        java.util.Iterator<RegularCourses> regsItr = regs.iterator();
        while( regsItr.hasNext() ){
            RegularCourses reg = regsItr.next();
            this.RegTableModel.addRow( new Object[]{reg.getSemester().getSemester(), this.RegEditor.toString( reg.getCourses().toArray() ) } );
        }
        
        java.util.ListIterator<CandidateInterface> candItr = cands.listIterator();
        while( candItr.hasNext() ){
            CandidateInterface cand = candItr.next();
            this.BackTableModel.addRow( new Object[]{ cand.getCandidateID(), this.BackEditor.toString( cand.getBackPapers() ) } );
        }
        
    }
    
    /** @return the return status of this dialog - one of RET_OK or RET_CANCEL */
    public int getReturnStatus() {
        return returnStatus;
    }

    public void setProgram(final String Program) {
        if( this.ProgramCombo.getItemCount() == 0 )
            this.ProgramCombo.addItem(Program);
        else{
            this.ProgramCombo.removeItemAt( this.ProgramCombo.getSelectedIndex() );
            this.ProgramCombo.addItem( Program );
        }
        this.RegEditor.setProgram(Program);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        CollegeText = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        ProgramCombo = new javax.swing.JComboBox();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        reuseCheck = new javax.swing.JCheckBox();
        CollegeCombo = new javax.swing.JComboBox();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        RegularTable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jSplitPane2 = new javax.swing.JSplitPane();
        jPanel6 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        BackTable = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        CentreCombo = new javax.swing.JComboBox();

        setTitle("College Form");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("College");

        CollegeText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                CollegeTextFocusLost(evt);
            }
        });

        jLabel2.setText("Program");

        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        reuseCheck.setText("use Similar Course");
        reuseCheck.setEnabled(false);
        reuseCheck.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                reuseCheckItemStateChanged(evt);
            }
        });

        CollegeCombo.setEnabled(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(reuseCheck)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CollegeCombo, 0, 239, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(reuseCheck)
                .addComponent(CollegeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Del");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton1)
            .addComponent(jButton2)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(29, 29, 29)
                .addComponent(jButton2)
                .addGap(66, 66, 66))
        );

        jSplitPane1.setLeftComponent(jPanel4);

        jPanel5.setLayout(new java.awt.BorderLayout());

        RegularTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Semester", "Courses"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        RegularTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(RegularTable);
        RegularTable.getColumnModel().getColumn(1).setCellEditor(this.RegEditor);

        jPanel5.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jSplitPane1.setRightComponent(jPanel5);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 396, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Regular", jPanel1);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jButton3.setText("Add");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Del");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton3)
            .addComponent(jButton4)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addContainerGap(175, Short.MAX_VALUE))
        );

        jSplitPane2.setLeftComponent(jPanel6);

        jPanel7.setLayout(new java.awt.BorderLayout());

        BackTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CandidateID", "BackCourses"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        BackTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(BackTable);
        BackTable.getColumnModel().getColumn(1).setCellEditor(this.BackEditor);

        jPanel7.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jSplitPane2.setRightComponent(jPanel7);

        jPanel2.add(jSplitPane2, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Back", jPanel2);

        jLabel3.setText("Centre");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(251, Short.MAX_VALUE)
                .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancelButton)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CentreCombo, 0, 146, Short.MAX_VALUE)
                    .addComponent(CollegeText, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ProgramCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE)
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cancelButton, okButton});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(ProgramCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(CollegeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(CentreCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton)
                    .addComponent(okButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        doClose(RET_OK);
    }//GEN-LAST:event_okButtonActionPerformed
    
    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        doClose(RET_CANCEL);
    }//GEN-LAST:event_cancelButtonActionPerformed
    
    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        doClose(RET_CANCEL);
    }//GEN-LAST:event_closeDialog

    private void reuseCheckItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_reuseCheckItemStateChanged
        if( this.reuseCheck.isSelected() ){
            this.CollegeCombo.setEnabled( true );
        }
        else
            this.CollegeCombo.setEnabled( false );
}//GEN-LAST:event_reuseCheckItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if( this.isRegTableFilled() ){
            String[] array = {"",""};
            this.RegTableModel.addRow(array);
            this.RegEditor.onRowAddition( null );
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int index = this.RegularTable.getSelectedRow();
        if( index > -1 ){
            this.RegTableModel.removeRow(index);
            this.RegEditor.onRowDeleted(index);
        }
        else{
            javax.swing.JOptionPane.showMessageDialog( null, "Please select semester to be deleted", "Row not Selected...", javax.swing.JOptionPane.ERROR_MESSAGE );
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        int index = this.BackTable.getSelectedRow();
        if( index > -1 ){
            this.BackTableModel.removeRow(index);
            this.BackEditor.onRowDeleted(index);
        }
        else{
            javax.swing.JOptionPane.showMessageDialog( null, "Please select semester to be deleted", "Row not Selected...", javax.swing.JOptionPane.ERROR_MESSAGE );
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if( this.isBackTableFilled() ){
            String[] array = {"",""};
            this.BackTableModel.addRow(array);
            this.BackEditor.onRowAddition( null );
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void CollegeTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CollegeTextFocusLost
        this.RegEditor.setCollege( this.CollegeText.getText() );
    }//GEN-LAST:event_CollegeTextFocusLost
    
    private void doClose(int retStatus) {
        returnStatus = retStatus;
        setVisible(false);
        dispose();
    }
    
    private boolean isBackTableFilled(){
        return this.BackTable.getRowCount()<1 || !this.BackTable.getValueAt( this.BackTable.getRowCount()-1, 0 ).equals("");
    }
    
    private boolean isRegTableFilled(){
        return this.RegularTable.getRowCount() < 1 || ! this.RegularTable.getValueAt( this.RegularTable.getRowCount() -1, 0).equals("");
    }
    
    public final String getProgramName(){
        return this.ProgramCombo.getSelectedItem().toString();
    }
    
    public final String getCollegeName(){
        return this.CollegeText.getText();
    }
    
    public final CentreIdentifier getCentre(){
        return new CentreIdentifier( this.CentreCombo.getSelectedItem().toString(), 0 );// for now lets assume it is 0
    }
    
    public CollegeBackCandidates getBackCandidates( Program prg, College c ){
        CollegeBackCandidates Candidates = new CollegeBackCandidates( c, prg);
        java.util.List<BackCandidateForm> formList = this.BackEditor.getForms();
        for( int i=0; i<formList.size(); i++){
            BackCandidateForm form = formList.get(i);
            Candidate cand = new Candidate( this.BackTable.getValueAt(i, 0 ).toString(), prg, c ,puexamroutine.control.domain.interfaces.CandidateInterface.NON_REGULAR  ,puexamroutine.control.domain.interfaces.CandidateInterface.BACK_ONLY  );
            cand.addBackPapers( java.util.Arrays.asList(form.getCourses()) );
            Candidates.addBackPaperCandidate(cand);
        }
        return Candidates;        
    }
    
    public SemesterList getAddedSemesters( Program prg, College c ){
        SemesterList list = new SemesterList( c, prg );
        java.util.Iterator<RegularCourseForm> formItr = this.RegEditor.getForms().iterator();
        while( formItr.hasNext() ){
            list.addSemester( formItr.next().getRegularCourses() );
        }
        return list;
    }
    
    public final College getCollege( Program prg ){
        College c = new College( this.getCollegeName() );
        c.addPrograms_Center_Semesters_Back( prg, this.getCentre(), this.getAddedSemesters(prg,c), this.getBackCandidates(prg,c));
        return c;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable BackTable;
    private javax.swing.JComboBox CentreCombo;
    private javax.swing.JComboBox CollegeCombo;
    private javax.swing.JTextField CollegeText;
    private javax.swing.JComboBox ProgramCombo;
    private javax.swing.JTable RegularTable;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton okButton;
    private javax.swing.JCheckBox reuseCheck;
    // End of variables declaration//GEN-END:variables
    
    private int returnStatus = RET_CANCEL;
    private BackCoursesEditor BackEditor;
    private SemesterRegularCourseEditor RegEditor;
    private DefaultTableModel RegTableModel, BackTableModel;
    private Collection<College> Colleges;
}