
//                                  !! RAM !!

package puexamroutine.ui.form;

import java.util.*;
import puexamroutine.control.domain.CourseCode;
import javax.swing.JOptionPane;


/**
 *
 * @author  Sumit Shresth
 */
public class CourseCodeInputForm extends javax.swing.JDialog {
    
    public static final int OK = 1, CANCEL = 2;
    
    /** Creates new form CourseCodeInputForm */
    public CourseCodeInputForm(java.awt.Frame parent ) {
        super(parent, true );
        initComponents();
        this.setLocationRelativeTo( null );
    }
   
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        prefixText = new javax.swing.JFormattedTextField();
        CourseText = new javax.swing.JFormattedTextField();
        creditText = new javax.swing.JFormattedTextField();
        jButton2 = new javax.swing.JButton();
        selectCourses = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Course Code Entry Form");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel1.setText("Prefix");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Course");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel3.setText("Credit");

        jLabel4.setFont(new java.awt.Font("Arial Black", 1, 14));
        jLabel4.setText("-");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel5.setText(".");

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        try {
            prefixText.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("UUU")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        prefixText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                prefixTextKeyPressed(evt);
            }
        });

        CourseText.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        CourseText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                CourseTextKeyPressed(evt);
            }
        });

        creditText.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        creditText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                creditTextKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                creditTextKeyTyped(evt);
            }
        });

        jButton2.setText("CANCEl");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        selectCourses.setEnabled(false);
        selectCourses.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                selectCoursesItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jButton1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton2))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(prefixText, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(CourseText, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(18, 18, 18))
                                .addComponent(creditText))))
                    .addComponent(selectCourses, 0, 231, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(prefixText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CourseText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(creditText, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(selectCourses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         this.onClose();       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        this.onCancel();
    }//GEN-LAST:event_formWindowClosed

private void prefixTextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_prefixTextKeyPressed
        if( evt.getKeyChar() == CourseCode.PrimarySeparator ){
            this.CourseText.requestFocusInWindow();
        }
        else
            if( evt.getKeyChar() == java.awt.event.KeyEvent.VK_ESCAPE ){
                this.onCancel();
            }
}//GEN-LAST:event_prefixTextKeyPressed

private void CourseTextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CourseTextKeyPressed
    if( evt.getKeyChar() == CourseCode.SecondarySeparator ){
        this.creditText.requestFocusInWindow();
    }
    else
            if( evt.getKeyChar() == java.awt.event.KeyEvent.VK_ESCAPE ){
                this.onCancel();
            }
            else
                if( evt.getKeyChar() == java.awt.event.KeyEvent.VK_BACK_SPACE ){
                    if( this.CourseText.getText().length() == 0 ){
                        this.prefixText.requestFocusInWindow();
                        this.prefixText.setCaretPosition( this.prefixText.getText().length() -1 );                        
                    }
                }
}//GEN-LAST:event_CourseTextKeyPressed

private void creditTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_creditTextKeyTyped
    if( evt.getKeyChar() == '\n' )
        this.onClose();
}//GEN-LAST:event_creditTextKeyTyped

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    this.onCancel();
}//GEN-LAST:event_jButton2ActionPerformed

private void creditTextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_creditTextKeyPressed
            if( evt.getKeyChar() == java.awt.event.KeyEvent.VK_ESCAPE ){
                this.onCancel();
            }
            else
                if( evt.getKeyChar() == java.awt.event.KeyEvent.VK_BACK_SPACE ){
                    if( this.creditText.getText().length() == 0 ){
                        this.CourseText.requestFocusInWindow();
                    }
                }
}//GEN-LAST:event_creditTextKeyPressed

private void selectCoursesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_selectCoursesItemStateChanged
    /*/if( evt.getStateChange() == evt.SELECTED ){
        CourseCode c = (CourseCode) evt.getItem();                
        this.initialize(c);        
    //}*/
    String c = evt.getItem().toString();
    if( c.indexOf("(") > -1 )
        c = c.substring( 0, c.indexOf( "(" ) );
    
    this.initialize( new CourseCode(c) );
}//GEN-LAST:event_selectCoursesItemStateChanged
    
    public void initialize( CourseCode c ){
            this.prefixText.setValue( null );
            this.CourseText.setValue( null );
            this.creditText.setValue( null );
        if( c != null ){
            this.prefixText.setText( c.getPrefix() );
            this.CourseText.setText( c.getCode() );
            this.creditText.setText( c.getCourseCredit() );
        }
            this.prefixText.requestFocusInWindow();
    }
    
    public void initialize( CourseCode c, java.util.Map<CourseCode,String> courses ) throws Exception{
        this.setExistingCourseList( courses );
        this.initialize(c);
    }
    
    private void setExistingCourseList( java.util.Map<CourseCode,String> c ) throws Exception{
        if( c == null) 
            throw new Exception( "Course List is Empty" );
        if( c.isEmpty() ){
            throw new Exception( "No Course is present in this Group.\nPlease use Course Panel to input the course first." );
        }
        this.selectCourses.removeAllItems();
        this.selectCourses.setEnabled( true );
        
        java.util.Iterator<CourseCode> cItr = this.sort(c).iterator();
        
        while( cItr.hasNext() ){
            CourseCode temp = cItr.next();            
            String text = temp.toString();
            if( ! ( c.get( temp ) == null || c.get( temp ).equals("") ) ){
                text += "("+c.get(temp)+")";
            }
            this.selectCourses.addItem( text );
        }
        
        // since existing course is inputted, so, allow user to only select from it n not actually create new course from here.
        this.prefixText.setEditable( false );
        this.CourseText.setEditable( false );
        this.creditText.setEditable( false );
    }
    
    private ArrayList<CourseCode> sort( Map<CourseCode,String> c ){
        
        HashSet<String> uniqueCourses = getUniqueCourses(c);
        
        Object[] courses = uniqueCourses.toArray();        
        
        Arrays.sort(courses);
        
        ArrayList<CourseCode> list = new ArrayList<CourseCode>();
        for( int i=0; i<courses.length; i++ ){
            list.addAll( this.getCourseCodes( courses[i].toString(), c ));
        }
        
        return list;
    }
    
    private final Collection<CourseCode> getCourseCodes( String Course, java.util.Map<CourseCode,String> c ){
        Iterator<CourseCode> courseItr = c.keySet().iterator();
        java.util.Collection<CourseCode> ret = new java.util.HashSet<CourseCode>();
        while( courseItr.hasNext() ){
            CourseCode temp = courseItr.next();
            if( c.get( temp ).equals( Course ) ){
                ret.add(temp);
            }
        }
        return ret;
    }
    
    private final HashSet<String> getUniqueCourses(Map<CourseCode, String> c) {
        java.util.Iterator<String> temp = c.values().iterator();
        java.util.HashSet<String> uniqueCourses = new java.util.HashSet<String>();
        while (temp.hasNext()) {
            String t = temp.next();
            if (!uniqueCourses.contains(t)) {
                uniqueCourses.add(t);
            } else {
                continue;
            }
        }

        return uniqueCourses;
    }

    public final CourseCode getCourseCode(){
        CourseCode c = new CourseCode();
        c.setPrefix( this.prefixText.getValue().toString() );
        c.setCode( this.CourseText.getValue().toString() );
        c.setCourseCredit( this.creditText.getValue().toString() );
        return c;
    }
    
    private boolean commit(){
        try{            
            this.CourseText.commitEdit();
            this.prefixText.commitEdit();
            this.creditText.commitEdit();
            return true;
        }
        catch( Exception e ){
            JOptionPane.showMessageDialog( null, "Wrong Value was inputted\n"+e.getMessage(), "Input Error", JOptionPane.ERROR_MESSAGE );
            return false;
        }
    }
    
    public final int getReturnStatus(){
        return this.status;
    }
    
    private void onClose(){
        if( this.commit() ){
            this.status = this.OK;
            this.setVisible( false );
        }
    }
    
    private void onCancel(){        
            this.status = this.CANCEL;
            this.setVisible( false );        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField CourseText;
    private javax.swing.JFormattedTextField creditText;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JFormattedTextField prefixText;
    private javax.swing.JComboBox selectCourses;
    // End of variables declaration//GEN-END:variables
    private int status;
}