
//                          !! RAM !!

package puexamroutine.ui.form;

import javax.swing.JOptionPane;
import puexamroutine.control.domain.*;

/**
 *
 * @author  Sumit Shresth
 */
public class CourseInputForm extends javax.swing.JDialog {
    /** A return status code - returned if Cancel button has been pressed */
    public static final int RET_CANCEL = 0;
    /** A return status code - returned if OK button has been pressed */
    public static final int RET_OK = 1;

    /** Creates new form CourseInputForm */
    public CourseInputForm(java.awt.Frame parent, java.util.Collection<Group> grp ) {
        super(parent, true);
        initComponents();        
        this.addGroups(grp);
        super.setLocationRelativeTo( null );
    }
    
    private void addGroups( java.util.Collection<Group> grp ){
        java.util.Iterator<Group> grpItr = grp.iterator();
        while( grpItr.hasNext() ){
            this.examGrp.addItem( grpItr.next() );
        }
    }

    /** @return the return status of this dialog - one of RET_OK or RET_CANCEL */
    public int getReturnStatus() {
        return returnStatus;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        courseCodeInputPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        prefixText = new javax.swing.JFormattedTextField();
        CourseText = new javax.swing.JFormattedTextField();
        creditText = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        courseName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        examGrp = new javax.swing.JComboBox();

        setTitle("Course Input Form");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        courseCodeInputPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Course Code"));

        jLabel1.setText("PREFIX");

        jLabel2.setText("COURSE");

        jLabel3.setText("CREDIT");

        try {
            prefixText.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("UUU")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        prefixText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prefixTextActionPerformed(evt);
            }
        });
        prefixText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                prefixTextKeyPressed(evt);
            }
        });

        CourseText.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("0"))));
        CourseText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                CourseTextKeyPressed(evt);
            }
        });

        creditText.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        creditText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                creditTextKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout courseCodeInputPanelLayout = new javax.swing.GroupLayout(courseCodeInputPanel);
        courseCodeInputPanel.setLayout(courseCodeInputPanelLayout);
        courseCodeInputPanelLayout.setHorizontalGroup(
            courseCodeInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(courseCodeInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(courseCodeInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(courseCodeInputPanelLayout.createSequentialGroup()
                        .addComponent(prefixText, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(CourseText, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(creditText, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE))
                    .addGroup(courseCodeInputPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(107, 107, 107)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                        .addComponent(jLabel3)))
                .addContainerGap())
        );
        courseCodeInputPanelLayout.setVerticalGroup(
            courseCodeInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(courseCodeInputPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(courseCodeInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(courseCodeInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prefixText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(creditText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CourseText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel4.setText("Course Name");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel5.setText("Exam Group");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(courseCodeInputPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(courseName, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(examGrp, 0, 230, Short.MAX_VALUE)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cancelButton, okButton});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(courseCodeInputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(courseName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(examGrp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton)
                    .addComponent(okButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        doClose(RET_OK);
    }//GEN-LAST:event_okButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        this.onCancel();
    }//GEN-LAST:event_cancelButtonActionPerformed

    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        this.onClose();
    }//GEN-LAST:event_closeDialog

private void prefixTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prefixTextActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_prefixTextActionPerformed

private void prefixTextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_prefixTextKeyPressed
        if( evt.getKeyChar() == CourseCode.PrimarySeparator ){
            this.CourseText.requestFocusInWindow();
        }
        else
            if( evt.getKeyChar() == java.awt.event.KeyEvent.VK_ESCAPE ){
                this.onCancel();
            }
}//GEN-LAST:event_prefixTextKeyPressed

private void CourseTextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CourseTextKeyPressed
    if( evt.getKeyChar() == CourseCode.SecondarySeparator ){
        this.creditText.requestFocusInWindow();
    }
    else
            if( evt.getKeyChar() == java.awt.event.KeyEvent.VK_ESCAPE ){
                this.onCancel();
            }
            else
                if( evt.getKeyChar() == java.awt.event.KeyEvent.VK_BACK_SPACE ){
                    if( this.CourseText.getText().length() == 0 ){
                        this.prefixText.requestFocusInWindow();
                        this.prefixText.setCaretPosition( this.prefixText.getText().length() -1 );                        
                    }
                }
}//GEN-LAST:event_CourseTextKeyPressed

private void creditTextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_creditTextKeyPressed
            if( evt.getKeyChar() == java.awt.event.KeyEvent.VK_ESCAPE ){
                this.onCancel();
            }
            else
                if( evt.getKeyChar() == java.awt.event.KeyEvent.VK_BACK_SPACE ){
                    if( this.creditText.getText().length() == 0 ){
                        this.CourseText.requestFocusInWindow();
                    }
                }
}//GEN-LAST:event_creditTextKeyPressed

    private void doClose(int retStatus) {
        returnStatus = retStatus;
        setVisible(false);
        dispose();
    }    
    
    private void onClose(){
        if( this.commit() ){
            this.returnStatus = this.RET_OK;
            this.setVisible( false );
        }
    }
    
    private void onCancel(){        
            this.returnStatus = this.RET_CANCEL;
            this.setVisible( false );        
    }
    
    private boolean commit(){
        try{            
            this.CourseText.commitEdit();
            this.prefixText.commitEdit();
            this.creditText.commitEdit();
            return true;
        }
        catch( Exception e ){
            JOptionPane.showMessageDialog( null, "Wrong Value was inputted\n"+e.getMessage(), "Input Error", JOptionPane.ERROR_MESSAGE );
            return false;
        }
    }
    
    public final CourseCode getCourseCode(){
        CourseCode c = new CourseCode();
        c.setPrefix( this.prefixText.getValue().toString() );
        c.setCode( this.CourseText.getValue().toString() );
        c.setCourseCredit( this.creditText.getValue().toString() );
        return c;
    }
    
    public final Course getCourse(){
        return new Course( this.getCourseCode(), (Group)this.examGrp.getSelectedItem(), this.courseName.getText() );
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField CourseText;
    private javax.swing.JButton cancelButton;
    private javax.swing.JPanel courseCodeInputPanel;
    private javax.swing.JTextField courseName;
    private javax.swing.JFormattedTextField creditText;
    private javax.swing.JComboBox examGrp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton okButton;
    private javax.swing.JFormattedTextField prefixText;
    // End of variables declaration//GEN-END:variables

    private int returnStatus = RET_CANCEL;    
}
