
//                          !! RAM !!

package puexamroutine.ui.form;

import java.awt.HeadlessException;
import javax.swing.JOptionPane;
import java.util.HashMap;
import java.util.Arrays;
import puexamroutine.control.domain.*;
import puexamroutine.ui.form.editors.CourseCodeEditor;

/**
 *
 * @author  Sumit Shresth
 */
public class RegularCourseForm extends javax.swing.JDialog implements java.io.Serializable {
    /** A return status code - returned if Cancel button has been pressed */
    public static final int RET_CANCEL = 0;
    /** A return status code - returned if OK button has been pressed */
    public static final int RET_OK = 1;
    
    /** Creates new form RegularCourseForm */
    public RegularCourseForm(java.awt.Frame parent, final String Program, final String Sem, final String College ) {
        super(parent, true);
        initComponents();
        this.TableModel = (javax.swing.table.DefaultTableModel) this.Table.getModel();
        this.setLocationRelativeTo( null );
        setProgram(Program);
        setSemester(Sem);
        setCollege(College);
    }
    
    public RegularCourseForm(java.awt.Frame parent, final String Program, final String Sem, final String College, final java.util.Map<CourseCode,String> grpCourses ) {
        this(parent, Program, Sem, College);
        try{
            this.CourseEditor.addSelectCourses(grpCourses);
        }
        catch( Exception e ){
            this.ERROR_MESSAGE = e.getMessage();
        }
    }
    
    public RegularCourseForm(java.awt.Frame parent, final Semester Sem, final java.util.Map<CourseCode,String> grpCourses ){
        this( parent, Sem.getProgram().getProgramName(), Sem.getSemester(), Sem.getCollege().getCollegeName(), grpCourses );
        this.initialize(Sem);
    }
    
    public void initialize( Semester sem ){
        this.setProgram( sem.getProgram().getProgramName() );
        this.setCollege( sem.getCollege().getCollegeName() );
        this.setSemester( sem.getSemester() );
        while( this.Table.getRowCount() > 0 ){
            this.TableModel.removeRow( 0 );
        }

        CourseCode[] cArray = sem.getRegularCourses().getCourses().toArray( new CourseCode[]{});
        java.util.List<CourseCode> courses = Arrays.asList( cArray );
        this.CourseEditor.addCourses( courses );
        
        for( int i=0; i<cArray.length; i++ ){
            this.TableModel.addRow( new Object[]{ i, cArray[i], sem.getRegularCourses().getTotalStudents(cArray[i])} );
        }
    }
    
    /** @return the return status of this dialog - one of RET_OK or RET_CANCEL */
    public int getReturnStatus() {
        return returnStatus;
    }

    public void setCollege(final String College) {
        if (College != null) {
            this.college.setText(College);
            this.college.setEditable(false);
        }
    }

    public void setProgram(final String Program) {
        if (Program != null) {
            this.prg.setText(Program);
            this.prg.setEditable(false);
        }
    }

    public void setSemester(final String Sem) {
        if (Sem != null) {
            this.sem.setText(Sem);
            this.sem.setEditable(false);
        }
    }
 
    private void addRow() {
        if( this.ERROR_MESSAGE != null ){
            javax.swing.JOptionPane.showMessageDialog(null, this.ERROR_MESSAGE, "Course Code Not present", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (this.isFilled()) {
            Object[] Value = {++this.courseCounter, "", 0};
            this.TableModel.addRow(Value);            
        }
    }

    private void delRow() throws HeadlessException {
        int index = this.Table.getSelectedRow();
        if (index > -1) {
            this.TableModel.removeRow(index);
            this.courseCounter--;
            this.CourseEditor.onRowDeleted(index);
        } else {
            JOptionPane.showMessageDialog(null, "Please select row", "row not selected", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        prg = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        college = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        sem = new javax.swing.JTextField();
        jSplitPane1 = new javax.swing.JSplitPane();
        westPanel = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        EastPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();

        setTitle("Regular Course Form");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Program");

        jLabel2.setText("College");

        jLabel3.setText("Semester");

        jButton1.setText("ADD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("DEL");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout westPanelLayout = new javax.swing.GroupLayout(westPanel);
        westPanel.setLayout(westPanelLayout);
        westPanelLayout.setHorizontalGroup(
            westPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton1)
            .addComponent(jButton2)
        );
        westPanelLayout.setVerticalGroup(
            westPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(westPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jButton1)
                .addGap(28, 28, 28)
                .addComponent(jButton2)
                .addContainerGap(121, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(westPanel);

        EastPanel.setLayout(new java.awt.BorderLayout());

        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Course", "TotalCandidates"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Table.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TableKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(Table);
        Table.getColumnModel().getColumn(1).setCellEditor(this.CourseEditor);

        EastPanel.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jSplitPane1.setRightComponent(EastPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 517, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(prg, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sem, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(college, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cancelButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cancelButton, okButton});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(prg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(sem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(college, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(okButton)
                    .addComponent(cancelButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        doClose(RET_OK);
    }//GEN-LAST:event_okButtonActionPerformed
    
    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        doClose(RET_CANCEL);
    }//GEN-LAST:event_cancelButtonActionPerformed
    
    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        doClose(RET_CANCEL);
    }//GEN-LAST:event_closeDialog

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        delRow();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        addRow();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void TableKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TableKeyPressed
        final int DOWN_KEY = 40;
        if( evt.getKeyChar() == java.awt.event.KeyEvent.VK_DELETE ){
            this.delRow();
            return;
        }
        if( this.Table.getSelectedRow() < this.Table.getModel().getRowCount() - 1 ){            
            return;
        }
        if( evt.getKeyCode() == DOWN_KEY ){
            this.addRow();
        }   
    }//GEN-LAST:event_TableKeyPressed
    
    private void doClose(int retStatus) {
        returnStatus = retStatus;
        setVisible(false);
        dispose();
    }
    
    private boolean isFilled(){
        return Table.getRowCount() == 0 || !this.Table.getValueAt( Table.getRowCount() -1, 1 ).equals("");
    }
    
    public HashMap<CourseCode,Integer> getCourses(){
        try{
            HashMap<CourseCode,Integer> pair = new HashMap<CourseCode,Integer>();
            for( int i=0; i<this.CourseEditor.getForms().size(); i++ ){
                int net = Integer.parseInt( this.TableModel.getValueAt(i, 2).toString() );
                pair.put( this.CourseEditor.getForms().get(i), net );
            }
            return pair;
        }
        catch( Exception e ){
            return null;
        }
    }
    
    public Semester getRegularCourses(){
        HashMap pair = this.getCourses();
        Semester sem = new Semester( this.sem.getText(),new College(this.college.getText()), new Program(this.prg.getText()));        
        sem.setRegularCourses( new RegularCourses(sem.getCollege(),sem.getProgram(), sem, pair ) );
        return sem;
    }
    
    public javax.swing.JTable getTable(){
        return this.Table;
    }
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel EastPanel;
    private javax.swing.JTable Table;
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField college;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JButton okButton;
    private javax.swing.JTextField prg;
    private javax.swing.JTextField sem;
    private javax.swing.JPanel westPanel;
    // End of variables declaration//GEN-END:variables
    
    private int returnStatus = RET_CANCEL;
    private javax.swing.table.DefaultTableModel TableModel = null;
    private java.lang.Integer courseCounter = 0;
    private CourseCodeEditor CourseEditor = new CourseCodeEditor();        
    private String ERROR_MESSAGE = null;
}