
//                              !! RAM !!

package puexamroutine.ui.components;
import javax.swing.*;

/**
 *
 * @author  Sumit Shresth
 */
public class MatrixListPanel extends JPanel
                            implements MultiLineComponent{
    
    /** Creates new form MatrixListPanel */
    public MatrixListPanel() {        
        initComponents();             
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        list = new javax.swing.JList();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.PAGE_AXIS));

        list.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        list.setModel(this.model );
        list.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        list.setToolTipText("");
        list.setLayoutOrientation(javax.swing.JList.HORIZONTAL_WRAP);
        list.setVisibleRowCount(-1);
        jScrollPane1.setViewportView(list);

        add(jScrollPane1);
    }// </editor-fold>//GEN-END:initComponents
    
    public void addElement( String element ){
        if( !this.model.contains(element) ){
            /*if( this.model.size() > 0 )
                this.model.addElement("    ");*/
            this.model.addElement( element );        
        }
    }
    
    public void removeElement( String element ){
        this.model.removeElement( element );
    }
    
    public void addElements( String[] elements ){
        for( int i=0; i<elements.length; i++ )
            this.addElement( elements[i] );
    }
    
    public void add( Object values ){
        this.value = values.toString();
        String[] array = values.toString().split("/");                
        this.addElements(array);
    }
    
    public void remove( Object values ){
        this.removeElement( values.toString() );
    }
    
    public java.awt.Component getComponent(){
        return this;
    }
    
    public void removeAll(){        
        this.model.removeAllElements();        
        list.updateUI();
    }
    
    public boolean exists( Object values ){
        if( this.value == null ) return false;            
        return this.value.equals(values);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList list;
    // End of variables declaration//GEN-END:variables
    private DefaultListModel model = new DefaultListModel();
    private String value = null;
}