
//                          !! RAM !!

package puexamroutine.ui;

import puexamroutine.ui.form.editors.CourseCodeEditor;
import javax.swing.JOptionPane;
import javax.swing.event.*;
import puexamroutine.ui.form.CourseInputForm;

/**
 * 
 * This class is for the dealing with the courses in the system.
 *
 * @author  Sumit Shresth
 */
public class CoursePanel extends javax.swing.JPanel {
    
    private final boolean DEBUG = false;

    /** Creates new form CouirsePanel */
    public CoursePanel() {
        initComponents();
    }
    
    public boolean initialize( puexamroutine.control.database.DatabaseWriter DbWrite, puexamroutine.control.domain.list.CourseList courseMap,java.util.Collection<puexamroutine.control.domain.Group> grps ){
        this.DbWriter = DbWrite;        
        this.removeAllCourses();
        return this.setCourses( courseMap,grps );
    }
    
    private void removeAllCourses(){
        while( this.TableModel.getRowCount() > 0 ){
            this.TableModel.removeRow( 0 );
        }
        this.courseCounter = 0;
    }
    
    public boolean setCourses( puexamroutine.control.domain.list.CourseList courseMap, java.util.Collection<puexamroutine.control.domain.Group> grps ){
        try{            
            this.grps.clear();
            this.grps.addAll(grps);
            java.util.Iterator<puexamroutine.control.domain.Course> courseItr = courseMap.getCourses().iterator();
            while( courseItr.hasNext() ){
                puexamroutine.control.domain.Course c = courseItr.next();
                this.TableModel.addRow( new Object[]{ c.getCourseCode(), c.getCourseName(), c.getGroup() } );
                this.CourseEditor.addCourse(c.getCourseCode());
            }            
            return true;
        }
        catch( Exception e ){
            return false;
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        northpanel = new javax.swing.JPanel();
        addBtn = new javax.swing.JButton();
        delBtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        courseTable = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        addBtn.setText("Add");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });
        northpanel.add(addBtn);

        delBtn.setText("Del");
        delBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delBtnActionPerformed(evt);
            }
        });
        northpanel.add(delBtn);

        jButton1.setText("Find");
        jButton1.setToolTipText("search Course Code");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        northpanel.add(jButton1);

        add(northpanel, java.awt.BorderLayout.PAGE_START);

        courseTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Course Code", "Course", "Group"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                true, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        courseTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(courseTable);
        courseTable.getColumnModel().getColumn(0).setCellEditor(this.CourseEditor);
        this.TableModel = (javax.swing.table.DefaultTableModel) this.courseTable.getModel();
        this.TableModel.addTableModelListener( new javax.swing.event.TableModelListener() {
            public void tableChanged(TableModelEvent e) {
                if( e.getType() == e.UPDATE ){ // if update only
                    if(DEBUG)System.out.println("this is full explain of changed\ncol=="+e.getColumn()+"\t1strow"+e.getFirstRow()+"\t2nd row"+e.getLastRow() );
                    switch( e.getColumn() ){
                        case 0://course code collumn
                        //do nothing
                        break;
                        case 1://course code name collumn
                        onCourseNameChange(TableModel.getValueAt( e.getFirstRow(), 0).toString(), TableModel.getValueAt( e.getFirstRow(), 1).toString() );
                        break;
                    }
                }
            }
        });

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        this.addRow();
}//GEN-LAST:event_addBtnActionPerformed

private void delBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delBtnActionPerformed
        this.delRow();
}//GEN-LAST:event_delBtnActionPerformed

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    CourseInputForm tempForm = new CourseInputForm( null, this.grps );
    //tempForm.initialize( null , this.CourseEditor.getForms() );
    tempForm.setVisible( true );
    if( tempForm.getReturnStatus() == tempForm.RET_OK ){        
        int i;
        for( i=0; i<this.TableModel.getRowCount(); i++ ){            
            if( this.TableModel.getValueAt(i, 0).toString().equals( tempForm.getCourseCode().toString() ) ){                
                this.courseTable.setRowSelectionInterval( i, i );                
                break;
            }
        }
        if( i == this.TableModel.getRowCount() ){//not found
            JOptionPane.showMessageDialog(null, tempForm.getCourseCode()+" cannot be found", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
}//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JTable courseTable;
    private javax.swing.JButton delBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel northpanel;
    // End of variables declaration//GEN-END:variables

    private void addRow() {
        //if (this.isFilled()) { // dont use unfilled since it is not a compulsion to give the value for each course code.
            CourseInputForm tempForm = new CourseInputForm( null, this.grps );
            tempForm.setVisible( true );
            if( tempForm.getReturnStatus() == tempForm.RET_OK ){                                    
                if( ! this.DbWriter.addCourse( tempForm.getCourseCode().toString(), tempForm.getCourse().getCourseName(), tempForm.getCourse().getGroup().getFaculty(), tempForm.getCourse().getGroup().getLevel(), tempForm.getCourse().getGroup().getDiscipline()  ) )
                    JOptionPane.showMessageDialog(null, "course code cannot be added", "Error", JOptionPane.ERROR_MESSAGE);
                else{
                    ++this.courseCounter;
                    Object[] Value = { tempForm.getCourseCode().toString(), tempForm.getCourse().getCourseName(), tempForm.getCourse().getGroup().toString() };
                    this.TableModel.addRow(Value);
                    this.CourseEditor.addCourse( tempForm.getCourseCode() );
                }                
            }   
        //}
    }
    
    private boolean isFilled(){
        return this.courseTable.getRowCount() == 0 || !this.courseTable.getValueAt( courseTable.getRowCount() -1, 1 ).equals("");
    }
    
    private void delRow(){
        int index = this.courseTable.getSelectedRow();
        if (index > -1) {
            String c = this.courseTable.getValueAt( index, 0).toString();
            boolean state = this.DbWriter.deleteCourse( c );
            if( !state ){
                JOptionPane.showMessageDialog(null, c+" was not deleted", "Course Not deleted", JOptionPane.ERROR_MESSAGE);
                return;
            }
            this.TableModel.removeRow(index);
            this.courseCounter--;
            this.CourseEditor.onRowDeleted(index);
        } else {
            JOptionPane.showMessageDialog(null, "Please select row", "row not selected", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void onCourseNameChange( String CourseCode, String newCourseName ){
        try{
            if(this.DEBUG)System.out.println(CourseCode+" has been changed to "+newCourseName );
            boolean state=false;
            if( this.DbWriter.readCourses().keySet().contains( CourseCode ) ){//see if udpated course code is already present in course table
                state = this.DbWriter.updateCourseName(CourseCode, newCourseName);
            }
/*            
 * this code is cancelled since courses are added from this panel only.
 * so, no chance of courses not added.
 else{
                state = this.DbWriter.addCourse(CourseCode, newCourseName);                
            }*/
            if( ! state )
                JOptionPane.showMessageDialog( null, "The value could not be updated", "Error", JOptionPane.ERROR_MESSAGE );
        }
        catch( Exception e ){            
            JOptionPane.showMessageDialog( null, "The value could not be updated", "Error", JOptionPane.ERROR_MESSAGE );
        }
    }
    
    private CourseCodeEditor CourseEditor = new CourseCodeEditor();
    private javax.swing.table.DefaultTableModel TableModel = null;
    private java.lang.Integer courseCounter = 0;
    
    private puexamroutine.control.database.DatabaseWriter DbWriter = null;
    private java.util.Collection<puexamroutine.control.domain.Group> grps= new java.util.HashSet<puexamroutine.control.domain.Group>();;
}