
//                          !! RAM !!

package puexamroutine.ui;

import puexamroutine.control.database.DatabaseWriter;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import puexamroutine.ui.form.ExamCentreForm;
import puexamroutine.ui.form.CentreUpdateForm;
import puexamroutine.ui.form.CentreLimitUpdateForm;
import puexamroutine.control.domain.*;

/**
 *
 * @author  Sumit Shresth
 */
public class ExamCentrePanel extends javax.swing.JPanel {

    /** Creates new form ExamCentrePanel */
    public ExamCentrePanel() {
        initComponents();
        this.Model = (DefaultTableModel)this.CentreTable.getModel();
    }
    
    public void setDataLoader( DatabaseWriter c ){
        this.Writer = c;        
        update();
    }
        
    private void initialize() {
        java.util.HashMap<String, Integer> centres = this.Writer.getCentres();
        java.util.Iterator<String> centItr = centres.keySet().iterator();
        while (centItr.hasNext()) {
            String cent = centItr.next();
            this.Model.addRow(new Object[]{cent, centres.get(cent)});
        }
    }
    
    private void addCentre(){
        ExamCentreForm form = new ExamCentreForm( null );
        form.setVisible( true );
        if ( form.getReturnStatus() == form.RET_OK ){
            CentreIdentifier c = form.getCentre();
            if( this.Writer.addCentre( c.getCentreName(), c.getMaximumCentreLimit() + "" ) )
                this.addCentre(c);            
            else
                JOptionPane.showMessageDialog( null, c.getCentreName()+" could not be written" , "Error", JOptionPane.ERROR_MESSAGE );
        }
    }
    
    private void addCentre( final CentreIdentifier c ){
        this.Model.addRow( new Object[]{ c.getCentreName(), c.getMaximumCentreLimit() } );
    }

    public void update() {
        while (this.Model.getRowCount() > 0) {
            this.Model.removeRow(0);
        }
        initialize();
    }
    
    private void updateCentreName(){        
        int row = this.CentreTable.getSelectedRow();
        if( row == -1 ){
            JOptionPane.showMessageDialog( null, "Please select appropiate centre to update", "Centre Not Selected", JOptionPane.ERROR_MESSAGE );
            return;
        }
        final String cent = this.Model.getValueAt(row, 0 ).toString();
        CentreUpdateForm form = new CentreUpdateForm( null, cent );
        form.setVisible( true );
        if( form.getReturnStatus() == form.RET_OK ){
            final String newCent = form.getNewCentre();            
            if( this.Writer.updateCentreName(cent, newCent) ){
                this.Model.setValueAt( newCent, row, 0 );
            }
            else
                JOptionPane.showMessageDialog( null, "newCent cannot be written", "Error", JOptionPane.ERROR_MESSAGE );
        }
        else
            System.out.println("from else condn");
    }
    
    private void updateCentreLimit(){
        int row = this.CentreTable.getSelectedRow();
        if( row == -1 ){
            JOptionPane.showMessageDialog( null, "Please select appropiate centre to update", "Centre Not Selected", JOptionPane.ERROR_MESSAGE );
            return;
        }
        final String limit = this.Model.getValueAt(row, 1 ).toString();
        final String cent = this.Model.getValueAt(row, 0 ).toString();
        CentreLimitUpdateForm form = new CentreLimitUpdateForm( null, cent, limit );
        form.setVisible( true );
        if( form.getReturnStatus() == form.RET_OK ){
            final String newLimit = form.getNewLimit()+ "";
            if( this.Writer.updateCentreLimit( cent, newLimit)){
                this.Model.setValueAt( newLimit, row, 1 );
            }
            else
                JOptionPane.showMessageDialog( null, cent+" could not be updated", "Error", JOptionPane.ERROR_MESSAGE );
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        CentreTable = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        jButton1.setText("ADD");
        jButton1.setToolTipText("add new Centre");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);

        jButton2.setText("UPDATE CENTRE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);

        jButton3.setText("UPDATE LIMIT");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        CentreTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Centre", "Limit"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        CentreTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(CentreTable);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    this.addCentre();
}//GEN-LAST:event_jButton1ActionPerformed

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    this.updateCentreName();
}//GEN-LAST:event_jButton2ActionPerformed

private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    this.updateCentreLimit();
}//GEN-LAST:event_jButton3ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable CentreTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private DatabaseWriter Writer = null;    
    private DefaultTableModel Model = null;
}