
//                                      !! RAM !!

package puexamroutine.ui;


import java.awt.event.ActionEvent;
import java.awt.event.MouseEvent;
import javax.swing.tree.*;
import puexamroutine.control.domain.*;
import puexamroutine.control.database.DatabaseWriter;
import puexamroutine.control.domain.list.*;
import puexamroutine.ui.form.ExamCentreForm;
import javax.swing.JOptionPane;
import java.util.Iterator;
import java.util.Collection;
import java.util.HashMap;
import javax.swing.*;
import puexamroutine.ui.form.*;
import puexamroutine.ui.components.SearchComponent;
import javax.swing.JPopupMenu;

/**
 *
 * @author  Sumit Shresth
 */
public class ExamCentreTree extends javax.swing.JPanel {
    
    /** Creates new form ExamCentreTree */
    public ExamCentreTree( DatabaseWriter write ) {
        this.Writer = write;
        this.Model = new DefaultTreeModel( this.Root );
        initComponents();
        this.initializeMenus();
    }
    
    public void initializeMenus(){
        this.RootMenu = new JPopupMenu();
        JMenuItem addCentre = new JMenuItem("add Centre");
        addCentre.addActionListener( new java.awt.event.ActionListener() {
            public void actionPerformed(ActionEvent e) {
                addCentre();
            }
        });
        this.RootMenu.add( addCentre );        
        JMenuItem removeAllCentres = new JMenuItem("remove All Centres");
        //this.RootMenu.add( removeAllCentres );
        this.CentreMenu = new JPopupMenu();
        JMenuItem delCentre = new JMenuItem("remove Centre");
        //this.CentreMenu.add( delCentre );
        JMenuItem updateCentre = new JMenuItem("update Centre");
        updateCentre.addActionListener( new java.awt.event.ActionListener() {
            public void actionPerformed(ActionEvent e) {
                updateCentreName();
            }
        });
        this.CentreMenu.add( updateCentre );
        this.LimitMenu = new JPopupMenu();
        JMenuItem updateLimit = new JMenuItem("update limit");
        updateLimit.addActionListener( new java.awt.event.ActionListener() {
            public void actionPerformed(ActionEvent e) {
                updateCentreLimit();
            }
        });
        this.LimitMenu.add( updateLimit );
    }
    
    public void setTreeList( CentreTable table ){
        this.Root.removeAllChildren();
        this.Tree.updateUI();
        Iterator<CentreIdentifier> centreItr = table.getCentres().iterator();
        while( centreItr.hasNext() ){
            this.addCentre( centreItr.next() );
        }
    }
    
    public void addCentre( CentreIdentifier centre ){
        DefaultMutableTreeNode centNode = new DefaultMutableTreeNode( centre.getCentreName() );
        DefaultMutableTreeNode maxLimitNode = new DefaultMutableTreeNode( centre.getMaximumCentreLimit() );
        centNode.add( maxLimitNode );
        this.Model.insertNodeInto(centNode, Root, 0 );
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Tree = new javax.swing.JTree();

        setLayout(new java.awt.BorderLayout());

        Tree.setModel(this.Model);
        Tree.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TreeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tree);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void TreeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TreeMouseClicked
        this.selectClickedNode(evt);
        if( this.isMenuClick(evt) ) onMenuClick(evt);
    }//GEN-LAST:event_TreeMouseClicked
    
    private final DefaultMutableTreeNode getSelectednode(){           
        return (DefaultMutableTreeNode) this.Tree.getLastSelectedPathComponent();
    }
    
    private void displayPopupMenu(final java.awt.event.MouseEvent evt, final javax.swing.JPopupMenu Menu ) {
        Menu.show(evt.getComponent(),evt.getX(), evt.getY());
    }

    private void onMenuClick(MouseEvent evt) {
        switch (this.Tree.getSelectionPath().getPathCount()) {
            case ROOT_NODE:
                this.displayPopupMenu(evt, RootMenu);
                break;
            case CENTRE_NODE:
                this.displayPopupMenu(evt, this.CentreMenu);
                break;
            case LIMIT_NODE:
                this.displayPopupMenu(evt, this.LimitMenu);
                break;
        }
    }
    
    private final boolean selectClickedNode(MouseEvent evt) {
        TreePath SelectedPath = this.Tree.getClosestPathForLocation(evt.getX(), evt.getY());
        if (SelectedPath == null) {
            return true;
        }
        if (this.Tree.getPathBounds(SelectedPath).contains(evt.getX(), evt.getY())) {            
            this.Tree.setSelectionPath(SelectedPath);
        } else {
            return true;
        }
        return false;
    }
    
    private final boolean isMenuClick( java.awt.event.MouseEvent evt ){
        return evt.getButton() == evt.BUTTON3;
    }
    
    private void addCentre(){
        ExamCentreForm form = new ExamCentreForm( null );
        form.setVisible( true );
        if ( form.getReturnStatus() == form.RET_OK ){
            CentreIdentifier c = form.getCentre();
            if( this.Writer.addCentre( c.getCentreName(), c.getMaximumCentreLimit() + "" ) )
                this.addCentre(c);            
            else
                JOptionPane.showMessageDialog( null, c.getCentreName()+" could not be written" , "Error", JOptionPane.ERROR_MESSAGE );
        }
    }
    
    private void updateCentreName(){
        DefaultMutableTreeNode node = this.getSelectednode();
        final String cent = node.toString();
        CentreUpdateForm form = new CentreUpdateForm( null, cent );
        form.setVisible( true );
        if( form.getReturnStatus() == form.RET_OK ){
            final String newCent = form.getNewCentre();            
            if( this.Writer.updateCentreName(cent, newCent) ){
                this.updateNode(node, newCent);
            }
            else
                JOptionPane.showMessageDialog( null, "newCent cannot be written", "Error", JOptionPane.ERROR_MESSAGE );
        }
        else
            System.out.println("from else condn");
    }
    
    private void updateCentreLimit(){
        DefaultMutableTreeNode node = this.getSelectednode();
        final String limit = node.toString();
        final String cent = node.getParent().toString();
        CentreLimitUpdateForm form = new CentreLimitUpdateForm( null, cent, limit );
        form.setVisible( true );
        if( form.getReturnStatus() == form.RET_OK ){
            final String newLimit = form.getNewLimit()+ "";
            if( this.Writer.updateCentreLimit( cent, newLimit)){
                this.updateNode(node, newLimit );
            }
            else
                JOptionPane.showMessageDialog( null, cent+" could not be updated", "Error", JOptionPane.ERROR_MESSAGE );
        }
    }
    
    private boolean updateNode( DefaultMutableTreeNode node, final String NewVal ){
        try{
            node.setUserObject( NewVal );
            this.Tree.updateUI();
            return true;
        }
        catch( Exception e ){
            return false;
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTree Tree;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
    private DefaultTreeModel Model = null;
    private DefaultMutableTreeNode Root = new DefaultMutableTreeNode("Exam Centres");
    private DatabaseWriter Writer = null;
    
    //Menus
    private JPopupMenu RootMenu, CentreMenu, LimitMenu;
    
    private final int ROOT_NODE=1;
    private final int CENTRE_NODE = 2;
    private final int LIMIT_NODE = 3;
}