
//                      !! RAM !!

package puexamroutine.ui;

import javax.swing.tree.*;
import javax.swing.JTabbedPane;
import java.awt.event.*;
import puexamroutine.control.domain.list.CourseList;
import puexamroutine.control.domain.routine.*;
import puexamroutine.ui.components.ButtonTabComponent;
import java.util.*;

/**
 *
 * @author  Sumit Shresth
 */
public class ExamRoutineTree extends javax.swing.JPanel {
    
    /** Creates new form ExamRoutineTree */
    public ExamRoutineTree( JTabbedPane tab ) {
        this.tab = tab;
        this.Root = new DefaultMutableTreeNode("Exam Routine");
        this.Model = new DefaultTreeModel( this.Root );
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Tree = new javax.swing.JTree();

        setLayout(new java.awt.BorderLayout());

        Tree.setModel(this.Model);
        Tree.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TreeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tree);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void TreeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TreeMouseClicked
        if( this.selectClickedNode(evt)) return;
        
        DefaultMutableTreeNode node = this.getSelectednode();
        if( node == this.Root ){
            this.display( "Over Exam Calander", OverAllExamCalander );
        }
        else if( node.getParent() == this.Root ){//group node
            this.display( node.toString(), this.GroupCalander.get( node.toString() ) );
        }
        else{
            this.display( node.toString(), this.PrgCalander.get(node.toString()));
        }
    }//GEN-LAST:event_TreeMouseClicked
    
    private void removeAllRoutines(){
        this.Root.removeAllChildren();
        this.Tree.updateUI();
        this.PrgCalander.clear();
        this.tab.removeAll();
        this.tab.updateUI();
    }
    
    public void setRoutines( ExaminationDayCalander calndr, Collection<GroupProgramRoutineList> grpRouts, puexamroutine.control.domain.list.CourseList Courses ){
        this.removeAllRoutines();
        OverAllExamCalander = new ExamCalander( Courses );
        OverAllExamCalander.display( calndr );                   
        addGroups(grpRouts, Courses);
        
        //open all nodes
        for( int i=0;i<this.Tree.getRowCount(); i++ ){
            this.Tree.expandRow( i );
            
        }
    }
    
    private void addGroups(Collection<GroupProgramRoutineList> grpRouts, CourseList Courses) {
        java.util.Iterator<GroupProgramRoutineList> grpRoutItr = grpRouts.iterator();
        while (grpRoutItr.hasNext()) {
            GroupProgramRoutineList grpRout = grpRoutItr.next();
            addGroup(Courses, grpRout);
        }
    }
    
    private void addGroup(CourseList Courses, GroupProgramRoutineList grpRout) {
        ExamCalander grpCalandar = new ExamCalander(Courses);
        grpCalandar.display(grpRout);
        this.GroupCalander.put(grpRout.getGroup().toString(), grpCalandar);
        DefaultMutableTreeNode grpnode = new DefaultMutableTreeNode(grpRout.getGroup().toString());
        this.Model.insertNodeInto(grpnode, Root, 0);
        addGroupPrograms(grpRout, Courses, grpnode);
    }
    
    private final void addGroupPrograms(GroupProgramRoutineList grpRout, CourseList Courses, DefaultMutableTreeNode grpnode) {
        java.util.Iterator<puexamroutine.control.domain.routine.ProgramRoutine> prgRoutItr = grpRout.getAllProgramRoutine().iterator();
        while (prgRoutItr.hasNext()) {
            ExamCalander prgCalander = new ExamCalander(Courses);
            addGroupProgram(prgRoutItr, prgCalander,grpnode);
        }
    }
    
    private void addGroupProgram(Iterator<ProgramRoutine> prgRoutItr, ExamCalander prgCalander, DefaultMutableTreeNode grpnode) {
        puexamroutine.control.domain.routine.ProgramRoutine prgRout = prgRoutItr.next();
        prgCalander.display(prgRout);
        final String prg = prgRout.getProgram().getProgramName();
        this.PrgCalander.put(prg, prgCalander);
        DefaultMutableTreeNode prgnode = new DefaultMutableTreeNode(prg);
        this.Model.insertNodeInto(prgnode, grpnode, 0);
    }
        
    private final DefaultMutableTreeNode getSelectednode(){           
        return (DefaultMutableTreeNode) this.Tree.getLastSelectedPathComponent();
    }
    
    private final boolean selectClickedNode(MouseEvent evt) {
        TreePath SelectedPath = this.Tree.getClosestPathForLocation(evt.getX(), evt.getY());
        if (SelectedPath == null) {
            return true;
        }
        if (this.Tree.getPathBounds(SelectedPath).contains(evt.getX(), evt.getY())) {            
            this.Tree.setSelectionPath(SelectedPath);
        } else {
            return true;
        }
        return false;
    }
    
    private void display( String Title, ExamCalander calander ){
        if( this.tab.indexOfComponent(calander) == -1 ){
            this.tab.add(Title, calander);            
            ButtonTabComponent.initTabComponent(tab, tab.indexOfComponent(calander));
        }
        this.tab.getModel().setSelectedIndex( this.tab.indexOfComponent(calander) );        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTree Tree;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
    private JTabbedPane tab = null;
    private DefaultMutableTreeNode Root = null;
    private DefaultTreeModel Model = null;
    private ExamCalander OverAllExamCalander = null;
    private HashMap<String, ExamCalander> PrgCalander = new HashMap<String, ExamCalander>();
    private HashMap<String, ExamCalander> GroupCalander = new HashMap<String, ExamCalander>();
}