
//                      !! RAM !!

package puexamroutine.ui;

import puexamroutine.control.domain.CourseCode;
import puexamroutine.control.domain.routine.*;
import javax.swing.table.*;
import puexamroutine.ui.components.*;
import java.awt.print.*;

/**
 *
 * @author  Sumit Shresth
 */
public class ExamCalander extends javax.swing.JPanel implements MultiLineComponentFactory{
    
    /** Creates new form ExamCalander */
    public ExamCalander( puexamroutine.control.domain.list.CourseList Courses ) {
        this.initializeRenderers();
        initComponents();
        this.model = (DefaultTableModel) this.Table.getModel();
        if( Courses != null && ! Courses.isEmpty() ){
            this.Courses = Courses;
        }        
    }

    private String getExams(puexamroutine.control.domain.CourseCode[] Exams) {
        String temp = null;
        if (Exams.length > 0) {
            temp = this.getExamsString(Exams);
        } else {
            temp = "NO EXAM";
        }
        return temp;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NorthPanel = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        TotalDaysText = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        NorthPanel.setLayout(new java.awt.BorderLayout());

        Title.setFont(new java.awt.Font("Tahoma", 1, 14));
        Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title.setText("Exam Calander");
        NorthPanel.add(Title, java.awt.BorderLayout.CENTER);

        add(NorthPanel, java.awt.BorderLayout.PAGE_START);

        jButton1.setText("Print");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Total Days");

        TotalDaysText.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TotalDaysText, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 223, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jButton1)
                .addComponent(TotalDaysText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        add(jPanel1, java.awt.BorderLayout.SOUTH);

        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Day", "Shift", "Exam List"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Table.setRowSorter(new CalanderSorter( Table.getModel() ));
        Table.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(Table);
        Table.getColumnModel().getColumn(0).setCellRenderer(this.ExamDayRenderer);
        Table.getColumnModel().getColumn(1).setCellRenderer(this.ExamDayShiftRenderer);
        Table.getColumnModel().getColumn(2).setCellRenderer(this.ExamListrenderer);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.printCalander();
    }//GEN-LAST:event_jButton1ActionPerformed
    
    public void display( ExaminationDayCalander calander ){        
        java.util.Iterator<puexamroutine.control.domain.ExamDayIdentifier> ExamDayItr = calander.getCalanderIterator();
        int i=1;
        while( ExamDayItr.hasNext() ){
            puexamroutine.control.domain.Day ExamDay = calander.getExamDay( ExamDayItr.next() );
            puexamroutine.control.domain.CourseCode[] Exams = ExamDay.getExamCourses();
            String temp = getExams(Exams);
            Object[] array = new Object[]{ i+"", ExamDay.getShift(), temp };
            this.model.addRow(array);
            
            /*
             *  MEMORY BUG:: HERE, CALANDER.DAY WAS CHHECKED TO BE EQUAL TO EXAMDAY.GETSHIFT
             *  USING MEMORY ==.
             *  THIS WORKED FINE FOR THE STAND ALONE SYSTEM, BUT WHEN RESULT FROM OTHER SYSTEM WAS TO BE DISPLAYED THIS DIDNT WORKED
             * SO, THE ERROR WAS VERY SERIOUS CAUSING CALANDER TO BE DISPLAYED WRONGLY
             * SO, IT IS REPLACED BY EQUALS
             */
            if( ExamDay.getShift().equals( calander.DAY ) ){
                i++;
            }
        }
        this.TotalDaysText.setText( calander.getTotalExamDays()+"" );
    }
    
    public void display( ProgramRoutine prgRout ){
        this.Title.setText( this.Title.getText()+" for Program " + prgRout.getProgram().getProgramName() );
        java.util.Iterator<puexamroutine.control.domain.Day> DayItr = prgRout.getExamList().iterator();
        
        while( DayItr.hasNext() ){
            puexamroutine.control.domain.Day day = DayItr.next();
            CourseCode[] courses = prgRout.getExams(day).getCoursesForDay();
            Object[] array = { day.getExamID().getDate()+"", day.getShift(), this.getExams(courses)};
            this.model.addRow(array);            
        }
        
        this.TotalDaysText.setText( prgRout.getExamList().size() + "" );
    }
    
    public void display( GroupProgramRoutine GroupExamCalander ){
        this.Title.setText( this.Title.getText()+" for "+GroupExamCalander.getGroup().toString() );
        java.util.Iterator<puexamroutine.control.domain.Day> DayItr = GroupExamCalander.getExamDayList().iterator();
        
        while( DayItr.hasNext() ){
            puexamroutine.control.domain.Day day = DayItr.next();
            CourseCode[] courses = GroupExamCalander.getExamCourses(day).toArray( new CourseCode[]{} );
            Object[] array = { day.getExamID().getDate()+"", day.getShift(), this.getExams(courses)};
            this.model.addRow(array);            
        }
        
        this.TotalDaysText.setText( GroupExamCalander.getExamDayList().size() + "" );
    }
    
    private void printCalander(){        
            try{
                if (! Table.print()) {
                    javax.swing.JOptionPane.showMessageDialog( null, "Printing Cancelled");
                }
            }
            catch ( PrinterException e ) {
                javax.swing.JOptionPane.showMessageDialog( null, "Cannot Print due to \n"+e.getMessage(), "Printing Error", javax.swing.JOptionPane.ERROR_MESSAGE );
            }
        /*    PrintingService prg = new PrintingService( this.Table );
            PrinterJob job = PrinterJob.getPrinterJob();
         job.setPrintable( prg );
         boolean ok = job.printDialog();
         if (ok) {             
        try { 
            job.print();
        } catch (java.awt.print.PrinterException e) {
            javax.swing.JOptionPane.showMessageDialog( null, "Cannot Print due to \n"+e.getMessage(), "Printing Error", javax.swing.JOptionPane.ERROR_MESSAGE );
        }
        }*/
    }
    
    private String getExamsString( puexamroutine.control.domain.CourseCode[] array ){
        String val = "";
        for( int i=0; i<array.length; i++ ){
            if( i > 0 )
                val += "/";
            String course;
            if( this.Courses == null || this.Courses.get( array[i] ) == null || this.Courses.get( array[i] ).equals( "" ) )
                course = array[i].toString();
            else
                course = this.Courses.get( array[i] );
            val += course;
        }
        return val;
    }
    
    public MultiLineComponent createMultiLineComponent(){
        return new MatrixListPanel();
    }
    
    public MultiLineComponent createMultiLineComponent( Object values ){
        MultiLineComponent com = this.createMultiLineComponent();
        com.add(values);
        return com;
    }
    
    private void initializeRenderers(){
        
        this.ExamListrenderer = new MultiLineRenderer( this );
        
        MultiLineComponentFactory ExamDayFact = new MultiLineComponentFactory(){
            public MultiLineComponent createMultiLineComponent(){
                return new SingleLine();
            }
    
            public MultiLineComponent createMultiLineComponent( Object values ){
                MultiLineComponent com = this.createMultiLineComponent();
                com.add(values);
                return com;
            }
        };
        this.ExamDayRenderer = new MultiLineRenderer( ExamDayFact );
        MultiLineComponentFactory ExamDayShiftFact = new MultiLineComponentFactory(){
            public MultiLineComponent createMultiLineComponent(){
                return new SingleLine();
            }
    
            public MultiLineComponent createMultiLineComponent( Object values ){
                MultiLineComponent com = this.createMultiLineComponent();
                com.add(values);
                return com;
            }
        };
        this.ExamDayShiftRenderer = new MultiLineRenderer( ExamDayShiftFact );
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel NorthPanel;
    private javax.swing.JTable Table;
    private javax.swing.JLabel Title;
    private javax.swing.JTextField TotalDaysText;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
    private MultiLineRenderer ExamListrenderer = null, ExamDayRenderer, ExamDayShiftRenderer;    
    private DefaultTableModel model = null;    
    private puexamroutine.control.domain.list.CourseList Courses =null;
}