
//                      !! RAM !!

package puexamroutine.ui;

import puexamroutine.control.domain.Group;
import javax.swing.table.DefaultTableModel;
import puexamroutine.ui.form.GroupInputForm;
import puexamroutine.control.Controller;
import javax.swing.JOptionPane;

/**
 * This panel deals with the exam groups.
 *
 * @author  Sumit Shresth
 */
public class GroupPanel extends javax.swing.JPanel {

    /** Creates new form GroupPanel */
    public GroupPanel() {
        initComponents();
    }
    
    public void initialize(  Controller cont ){
        this.controller = cont;
        update();
    }

    public void update() {
        while (this.GrpTable.getRowCount() > 0) {
            ((DefaultTableModel) this.GrpTable.getModel()).removeRow(0);
        }
        java.util.Iterator<Group> grpItr = this.controller.getGroupList().getGroups().iterator();
        while (grpItr.hasNext()) {
            Group grp = grpItr.next();
            ((DefaultTableModel) this.GrpTable.getModel()).addRow(new Object[]{grp.getFaculty(), grp.getLevel(), grp.getDiscipline()});
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        LeftPanel = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        GrpTable = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        jButton1.setText("ADD");
        jButton1.setToolTipText("add new Group");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("DEL");
        jButton2.setToolTipText("delete selected Group");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LeftPanelLayout = new javax.swing.GroupLayout(LeftPanel);
        LeftPanel.setLayout(LeftPanelLayout);
        LeftPanelLayout.setHorizontalGroup(
            LeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LeftPanelLayout.createSequentialGroup()
                .addGroup(LeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );
        LeftPanelLayout.setVerticalGroup(
            LeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LeftPanelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addContainerGap(200, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(LeftPanel);

        GrpTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Faculty", "Level", "Discipline"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        GrpTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(GrpTable);

        jSplitPane1.setRightComponent(jScrollPane1);

        add(jSplitPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    GroupInputForm form = new GroupInputForm( null, this.controller.getGroupList().getGroups() );
    form.setVisible( true );
    if( form.getReturnStatus() == form.RET_OK ){
        Group grp = form.getInputtedGroup();
        boolean st = this.controller.getDatabaseManager().addGroup( grp.getFaculty(), grp.getLevel(), grp.getDiscipline() );
        if( ! st ){
            JOptionPane.showMessageDialog(null, grp.toString()+ " could not be added", "Error Group Addition", JOptionPane.ERROR_MESSAGE );
        }
        else{
            ((DefaultTableModel)this.GrpTable.getModel()).addRow( new Object[]{ grp.getFaculty(), grp.getLevel(), grp.getDiscipline() } );
        }
    }
}//GEN-LAST:event_jButton1ActionPerformed

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    int row = this.GrpTable.getSelectedRow();
    if( row == -1 ){
        JOptionPane.showMessageDialog( null, "Row is not Selected. Please select the row/Group to be delected", "Row Not Selected", JOptionPane.ERROR_MESSAGE );
        return;
    }
    if( JOptionPane.showConfirmDialog( null, "Are you sure you want to delete the selected Group") != JOptionPane.OK_OPTION ){
        return;
    }
    boolean st = this.controller.getDatabaseManager().deleteDiscipline( this.GrpTable.getValueAt(row, 0).toString(), this.GrpTable.getValueAt(row, 1).toString(), this.GrpTable.getValueAt(row, 2).toString() );
    if( st ){
        ((DefaultTableModel)this.GrpTable.getModel()).removeRow(row);
    }
    else
        JOptionPane.showMessageDialog( null, "The Group Could not be deleted", "Group Not deleted", JOptionPane.ERROR_MESSAGE );
}//GEN-LAST:event_jButton2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable GrpTable;
    private javax.swing.JPanel LeftPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables

    private Controller controller = null;
}