
//                                  !! RAM !!

package puexamroutine.ui;

import javax.swing.event.ChangeEvent;
import puexamroutine.control.routinegeneration.interfaces.SystemStepState;
import java.awt.HeadlessException;
import javax.swing.JOptionPane;
import java.util.*;
import puexamroutine.control.Controller;
import javax.swing.SwingWorker;
import puexamroutine.control.interfaces.*;
import puexamroutine.ui.components.*;
import puexamroutine.control.schedule.Result;
import puexamroutine.ui.form.RemoteScheduleLocationIndentifierForm;

/**
 * This class is the basic frame.
 *
 * @author  Sumit Shresth
 */
public class MainFrame extends javax.swing.JFrame implements DomainListener, MonitorListener{
    
    private boolean DEBUG = false;
    
    /** Creates new form MainFrame */
    public MainFrame() throws Exception{        
        this.Dialog = new About( this );
        this.DatabaseSettings = new Database( this );
        this.initializeBackGroundImage();
        initComponents();     
        this.initializeFormView();
        this.setLocationRelativeTo( null );  
        initialize();
        this.FormVewBtn.setSelected( true );
        //Thread.setDefaultUncaughtExceptionHandler(MemoryErrorHandler);
    }

    public void initialize() {
        if (this.initializeBackEnds()) {
            this.DataTree.initialize(writer);
            this.DataTree.setDataLoader(controller);
            this.CenterTree = new ExamCentreTree(this.writer);
            this.CenterTree.setTreeList(this.controller.getCentres());
            this.CentreTreePanel.add(this.CenterTree);            
            
            // initialize form view components
            this.grpPanel.initialize(controller);
            this.ExamCentrePanel.setDataLoader(writer);
            this.prgPanel.initialize(controller);
            
            this.initializeCoursePanel();
        } else {
            this.disableAll();
            this.setVisible(true);            
            int result = JOptionPane.showConfirmDialog( null, "The database could not be properly connected.\nDo You Want to TroubleShoot it OR Close\nPress OK to continue and Cancel to close", "Confirm Continue", JOptionPane.YES_NO_OPTION );
            if( result == JOptionPane.NO_OPTION ){
                System.exit( 0 );
            }
            this.DatabaseSettings.showDatabaseSettings();
            if( this.DatabaseSettings.isChanged() ){
                //System.out.println("changed...");
                this.initialize();            
                this.enableAll();
            }/*
            else
                System.out.println("not changed...");*/
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel14 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        ForeGroundPanel = new javax.swing.JPanel();
        NorthPanel = new javax.swing.JPanel();
        CentrePanel = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        findBtn = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        FormVewBtn = new javax.swing.JRadioButton();
        TreeViewCombo = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        mingapLabel = new javax.swing.JLabel();
        minCombo = new javax.swing.JComboBox();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        maxgapLabel = new javax.swing.JLabel();
        MaxCombo = new javax.swing.JComboBox();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        ScheduleBtn = new javax.swing.JButton();
        AboutBtn = new javax.swing.JButton();
        CentralPanel = new javax.swing.JPanel();
        jSplitPane2 = new javax.swing.JSplitPane();
        InputPanel = new javax.swing.JPanel();
        TreeTab = new javax.swing.JTabbedPane();
        DataTreePanel = new javax.swing.JPanel();
        CentreTreePanel = new javax.swing.JPanel();
        coursePanel = new javax.swing.JPanel();
        DisplayPanel = new javax.swing.JPanel();
        centralTab = new javax.swing.JTabbedPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        EditMenu = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        ViewMenu = new javax.swing.JMenu();
        TreeView = new javax.swing.JRadioButtonMenuItem();
        FormView = new javax.swing.JRadioButtonMenuItem();
        MiscellneousMenu = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        remoteSchedulingCheck = new javax.swing.JCheckBoxMenuItem();
        remoteSchedulingEditMenu = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        jLabel14.setText("jLabel14");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("University Examination Routine Software");
        setIconImage(this.URGLogo);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setLayout(new java.awt.BorderLayout());
        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        ForeGroundPanel.setLayout(new java.awt.BorderLayout());

        NorthPanel.setOpaque(false);
        NorthPanel.setLayout(new java.awt.BorderLayout());
        ForeGroundPanel.add(NorthPanel, java.awt.BorderLayout.NORTH);

        CentrePanel.setOpaque(false);
        CentrePanel.setLayout(new java.awt.BorderLayout());

        jToolBar1.setFloatable(false);

        findBtn.setMnemonic('f');
        findBtn.setText("Find");
        findBtn.setToolTipText("find in Tree");
        findBtn.setFocusable(false);
        findBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        findBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        findBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findBtnActionPerformed(evt);
            }
        });
        jToolBar1.add(findBtn);
        jToolBar1.add(jSeparator3);

        FormVewBtn.setText("Form View");
        FormVewBtn.setFocusable(false);
        FormVewBtn.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        FormVewBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        FormVewBtn.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                FormVewBtnItemStateChanged(evt);
            }
        });
        jToolBar1.add(FormVewBtn);

        TreeViewCombo.setSelected(true);
        TreeViewCombo.setText("Tree View");
        TreeViewCombo.setFocusable(false);
        TreeViewCombo.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        TreeViewCombo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        TreeViewCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                TreeViewComboItemStateChanged(evt);
            }
        });
        jToolBar1.add(TreeViewCombo);
        jToolBar1.add(jSeparator1);

        mingapLabel.setLabelFor(minCombo);
        mingapLabel.setText("Minimum Gap");
        jToolBar1.add(mingapLabel);

        minCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        minCombo.setSelectedIndex(2);
        minCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minComboActionPerformed(evt);
            }
        });
        jToolBar1.add(minCombo);
        jToolBar1.add(jSeparator4);

        maxgapLabel.setLabelFor(MaxCombo);
        maxgapLabel.setText("Maximum Gap");
        jToolBar1.add(maxgapLabel);

        MaxCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20" }));
        MaxCombo.setSelectedIndex(6);
        MaxCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaxComboActionPerformed(evt);
            }
        });
        jToolBar1.add(MaxCombo);
        jToolBar1.add(jSeparator2);
        jToolBar1.add(jSeparator5);

        ScheduleBtn.setMnemonic('s');
        ScheduleBtn.setText("Schedule");
        ScheduleBtn.setFocusable(false);
        ScheduleBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ScheduleBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ScheduleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ScheduleBtnActionPerformed(evt);
            }
        });
        jToolBar1.add(ScheduleBtn);

        AboutBtn.setText("About");
        AboutBtn.setFocusable(false);
        AboutBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        AboutBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        AboutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AboutBtnActionPerformed(evt);
            }
        });
        jToolBar1.add(AboutBtn);

        CentrePanel.add(jToolBar1, java.awt.BorderLayout.PAGE_START);
        javax.swing.ButtonGroup ToolbarComboBtnGrp = new javax.swing.ButtonGroup();
        ToolbarComboBtnGrp.add( TreeViewCombo );
        ToolbarComboBtnGrp.add( FormVewBtn );

        CentralPanel.setLayout(new java.awt.BorderLayout());

        InputPanel.setLayout(new java.awt.BorderLayout());

        TreeTab.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                TreeTabStateChanged(evt);
            }
        });

        DataTreePanel.setLayout(new java.awt.BorderLayout());

        // initialize data tree
        this.DataTree = new ExamDataTree();
        javax.swing.JScrollPane scroll = new javax.swing.JScrollPane( this.DataTree );
        DataTreePanel.add( scroll );

        TreeTab.addTab("Data", DataTreePanel);

        CentreTreePanel.setLayout(new java.awt.BorderLayout());
        TreeTab.addTab("Centre", CentreTreePanel);

        coursePanel.setLayout(new java.awt.BorderLayout());
        TreeTab.addTab("Courses", coursePanel);
        this.coursePanel.add( this.courses );

        InputPanel.add(TreeTab, java.awt.BorderLayout.CENTER);

        jSplitPane2.setLeftComponent(InputPanel);

        DisplayPanel.setLayout(new java.awt.BorderLayout());

        centralTab.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        DisplayPanel.add(centralTab, java.awt.BorderLayout.CENTER);

        jSplitPane2.setRightComponent(DisplayPanel);

        CentralPanel.add(jSplitPane2, java.awt.BorderLayout.CENTER);

        CentrePanel.add(CentralPanel, java.awt.BorderLayout.CENTER);

        ForeGroundPanel.add(CentrePanel, java.awt.BorderLayout.CENTER);

        getContentPane().add(ForeGroundPanel, java.awt.BorderLayout.CENTER);

        fileMenu.setText("File");

        jMenu6.setText("Print");
        jMenu6.setToolTipText("menu to print routines");
        jMenu6.setEnabled(false);

        jMenuItem8.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, 0));
        jMenuItem8.setText("Print All Routines");
        jMenu6.add(jMenuItem8);

        jMenuItem9.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, 0));
        jMenuItem9.setText("Print Exam Calander");
        jMenu6.add(jMenuItem9);

        fileMenu.add(jMenu6);

        jMenuItem7.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, 0));
        jMenuItem7.setText("Exit");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        fileMenu.add(jMenuItem7);

        jMenuBar1.add(fileMenu);

        EditMenu.setText("Edit");

        jMenuItem10.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, 0));
        jMenuItem10.setText("Find");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        EditMenu.add(jMenuItem10);

        jMenuBar1.add(EditMenu);

        ViewMenu.setText("View");

        TreeView.setSelected(true);
        TreeView.setText("Tree View");
        TreeView.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                TreeViewItemStateChanged(evt);
            }
        });
        ViewMenu.add(TreeView);

        FormView.setText("Form View");
        FormView.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                FormViewItemStateChanged(evt);
            }
        });
        ViewMenu.add(FormView);

        jMenuBar1.add(ViewMenu);
        javax.swing.ButtonGroup grp = new javax.swing.ButtonGroup();
        grp.add( TreeView );
        grp.add( FormView );

        MiscellneousMenu.setText("Miscellanous");
        MiscellneousMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MiscellneousMenuActionPerformed(evt);
            }
        });
        MiscellneousMenu.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                MiscellneousMenuAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, 0));
        jMenuItem4.setText("DatabaseSettings");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        MiscellneousMenu.add(jMenuItem4);

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, 0));
        jMenuItem5.setText("Database");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        MiscellneousMenu.add(jMenuItem5);

        jMenu1.setText("remote schedule");

        remoteSchedulingCheck.setText("use remote");
        remoteSchedulingCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                remoteSchedulingCheckActionPerformed(evt);
            }
        });
        jMenu1.add(remoteSchedulingCheck);

        remoteSchedulingEditMenu.setText("edit remote");
        remoteSchedulingEditMenu.setEnabled(false);
        remoteSchedulingEditMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                remoteSchedulingEditMenuActionPerformed(evt);
            }
        });
        jMenu1.add(remoteSchedulingEditMenu);

        MiscellneousMenu.add(jMenu1);

        jMenuBar1.add(MiscellneousMenu);

        helpMenu.setText("Help");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, 0));
        jMenuItem1.setText("About");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        helpMenu.add(jMenuItem1);

        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, 0));
        jMenuItem6.setText("Version");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        helpMenu.add(jMenuItem6);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, 0));
        jMenuItem2.setText("License");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        helpMenu.add(jMenuItem2);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, 0));
        jMenuItem3.setText("Contact");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        helpMenu.add(jMenuItem3);

        jMenuBar1.add(helpMenu);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        onExit();
    }//GEN-LAST:event_formWindowClosing

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        this.Dialog.showAbout();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        this.Dialog.showContact();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        this.Dialog.showLicense();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        this.DatabaseSettings.showDatabaseSettings();
        if( this.DatabaseSettings.isChanged() ){
            //System.out.println("Is Change ");
            this.initialize();
            this.enableAll();
        }/*
        else
            System.out.println("Is not Change ");*/
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        this.DatabaseSettings.showDatabase();
        if( this.DatabaseSettings.isChanged() ){
            //System.out.println("Is Change ");
            this.initialize();
            this.enableAll();
        }/*
        else
            System.out.println("Is not Change ");*/
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void AboutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AboutBtnActionPerformed
        this.Dialog.showAbout();
    }//GEN-LAST:event_AboutBtnActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        this.Dialog.showVersion();
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void minComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minComboActionPerformed
        try{
            int min = Integer.parseInt( this.minCombo.getSelectedItem().toString() );
            this.controller.setMinimumGap(min);
        }
        catch( Exception e ){
            JOptionPane.showMessageDialog( null, "The Minimum gap could'nt be set", "Error", JOptionPane.ERROR_MESSAGE );
        }
    }//GEN-LAST:event_minComboActionPerformed

    private void MaxComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaxComboActionPerformed
        try{
            int max = Integer.parseInt( this.MaxCombo.getSelectedItem().toString() );
            this.controller.setMaxGap(max);
        }
        catch( Exception e ){
            JOptionPane.showMessageDialog( null, "The Maximum gap could'nt be set", "Error", JOptionPane.ERROR_MESSAGE );
        }
    }//GEN-LAST:event_MaxComboActionPerformed

    private void ScheduleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ScheduleBtnActionPerformed
        this.schedule();
    }//GEN-LAST:event_ScheduleBtnActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        onExit();
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        this.DataTree.find();
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void findBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findBtnActionPerformed
        this.DataTree.find();
}//GEN-LAST:event_findBtnActionPerformed

private void MiscellneousMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MiscellneousMenuActionPerformed
    
}//GEN-LAST:event_MiscellneousMenuActionPerformed

private void MiscellneousMenuAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_MiscellneousMenuAncestorAdded
// TODO add your handling code here:
}//GEN-LAST:event_MiscellneousMenuAncestorAdded

private void remoteSchedulingCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_remoteSchedulingCheckActionPerformed
    this.makeRemoteSchedule( true );
}//GEN-LAST:event_remoteSchedulingCheckActionPerformed

private void remoteSchedulingEditMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_remoteSchedulingEditMenuActionPerformed
    this.makeRemoteSchedule(false);
}//GEN-LAST:event_remoteSchedulingEditMenuActionPerformed

private void TreeViewItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_TreeViewItemStateChanged
    if( evt.getStateChange() == evt.SELECTED ){
        //System.out.println( "tree view selected..." );
        this.showTreeView();
        this.TreeViewCombo.setSelected( true );
    }
}//GEN-LAST:event_TreeViewItemStateChanged

private void FormViewItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_FormViewItemStateChanged
    if( evt.getStateChange() == evt.SELECTED ){
        //System.out.println( "tree view selected..." );
        this.showFormView();
        this.FormVewBtn.setSelected( true );
    }
}//GEN-LAST:event_FormViewItemStateChanged

private void FormVewBtnItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_FormVewBtnItemStateChanged
    if( evt.getStateChange() == evt.SELECTED ){
        //System.out.println( "tree view selected..." );
        this.showFormView();
        this.FormView.setSelected( true );
    }
}//GEN-LAST:event_FormVewBtnItemStateChanged

private void TreeViewComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_TreeViewComboItemStateChanged
    if( evt.getStateChange() == evt.SELECTED ){
        //System.out.println( "tree view selected..." );
        this.showTreeView();
        this.TreeView.setSelected( true );
    }
}//GEN-LAST:event_TreeViewComboItemStateChanged

private void TreeTabStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_TreeTabStateChanged
try{
        if( this.TreeTab.getSelectedComponent() == this.DataTreePanel ){
            if( this.controller != null )
                this.controller.reRead();
        }   
        else
            if( this.TreeTab.getSelectedComponent() == this.coursePanel ){
                if( this.controller != null ){
                    this.controller.reRead();
                    initializeCoursePanel();
                }
            }
    }
    catch( Exception e ){
        JOptionPane.showMessageDialog( null, "System could not read database.\nSo, The values in this tree may be older than expected\n"+e.getMessage(), "Loading Error", JOptionPane.ERROR_MESSAGE );
    }
}//GEN-LAST:event_TreeTabStateChanged

    private void showTreeView(){
        if( this.InputPanel.getComponent( 0 ) == this.TreeTab ){
            if(this.DEBUG)System.out.println("Tree Tab is already present");
        }
        else{
            this.InputPanel.removeAll();
            this.InputPanel.add( this.TreeTab );
            this.updateTreeView();
            this.InputPanel.updateUI();
        }
    }
    
    private void showFormView(){
        if( this.InputPanel.getComponent( 0 ) == this.TreeTab ){
            this.InputPanel.removeAll();
            this.controller.reRead();            
            this.InputPanel.add( this.FormViewTab );
            this.updateFormView();
            this.InputPanel.updateUI();
        }
        else
            if(this.DEBUG)System.out.println( "Form View is already present" );
    }
    
    private void updateFormView(){
        this.controller.reRead();
        this.grpPanel.update();
        this.initializeCoursePanel();
        this.ExamCentrePanel.update();
        this.prgPanel.update();
    }
    
    private void updateTreeView(){
        this.controller.reRead();
        this.DataTree.reload();
        this.initializeCoursePanel();
        this.CenterTree.setTreeList( this.controller.getCentres() );
    }
    
    private void initializeCoursePanel(){
        this.courses.initialize( writer, this.controller.getGroupList().getCourses_Code_Name_Mapping(), this.controller.getGroupList().getGroups() );
        this.formViewCourses.initialize( writer, this.controller.getGroupList().getCourses_Code_Name_Mapping(), this.controller.getGroupList().getGroups() );
    }

    private void initializeBackGroundImage(){        
        this.URGLogo = java.awt.Toolkit.getDefaultToolkit().createImage( "puexamroutine/ui/img/logo.png" );
    }
    
    private boolean initializeBackEnds(){
        try{
            int max = Integer.parseInt( this.MaxCombo.getSelectedItem().toString() );
            int min = Integer.parseInt( this.minCombo.getSelectedItem().toString() );
            this.controller = new Controller( DatabaseSettings.getDbURL(), DatabaseSettings.getDriver(),
                    DatabaseSettings.getUserName(), DatabaseSettings.getPassword(), DatabaseSettings.getCourseField(),
                    DatabaseSettings.getPrgField(), DatabaseSettings.getRegCourseTable(), DatabaseSettings.getCourseTable(),
                    DatabaseSettings.getSemField(), DatabaseSettings.getDatabaseName(), DatabaseSettings.getBackPaperTable(),
                    DatabaseSettings.getCandidateField(),DatabaseSettings.getProgramTable(),
                    DatabaseSettings.getFaculty(), DatabaseSettings.getLevel(), min, max );        
            this.writer = (puexamroutine.control.database.DatabaseWriter) this.controller.getDatabaseManager();            
            return true;
        }
        catch( Exception e ){
            JOptionPane.showMessageDialog( null, "There was problem with system initialization.\n"+e.getMessage(), "Initialization Error", JOptionPane.ERROR_MESSAGE );
            //System.exit( 0 );
            return false;
        }        
    }

    private void onExit() throws HeadlessException {
        int state = JOptionPane.showConfirmDialog(null, "Are you sure you want to close?", "Close Confirmation", JOptionPane.YES_NO_OPTION);
        if (state == JOptionPane.OK_OPTION) {
            System.exit(0);
        }
    }

    private void onSuccessfullScheduling( Result rs ) throws HeadlessException {
        if (this.RoutineTree == null) {
            this.RoutineTree = new ExamRoutineTree(this.centralTab);
            this.TreeTab.add("Routine", this.RoutineTree);
        }
        if( this.DEBUG )
            rs.getExamCalander().print();
        this.TreeTab.setSelectedComponent(this.RoutineTree);
        this.RoutineTree.setRoutines( rs.getExamCalander(), rs.getGroupRoutine(), this.controller.getGroupList().getCourses_Code_Name_Mapping() );
        this.TreeViewCombo.setSelected( true );
        Collection<puexamroutine.control.domain.Group> unsheduledgrps = rs.getunScheduledGroups();        
        if (unsheduledgrps.isEmpty()) {
            JOptionPane.showMessageDialog(null, "The value was successfully scheduled...");
        } else {
            Iterator<puexamroutine.control.domain.Group> grpitr = unsheduledgrps.iterator();
            String grps = "";
            while (grpitr.hasNext()) {
                puexamroutine.control.domain.Group grp = grpitr.next();
                grps += grp.getFaculty() + ":" + grp.getLevel() + ":" + grp.getDiscipline() + "\n";
            }
            JOptionPane.showMessageDialog(null, "Following could not be scheduled\n" + grps + "try increasing maximum days or decreasing minimum days", "Error", JOptionPane.ERROR_MESSAGE);
        }        
    }
    
    private void schedule(){        
        this.controller.setListener( this );
        this.userCancelled = false;
        SwingWorker<Result, Void> current_scheduler = this.getSchedulerThread();
        current_scheduler.execute();                        
        this.monitor.setVisible( true );                    
    }
    
    private void disableAll(){
        this.ScheduleBtn.setEnabled( false );
        this.minCombo.setEnabled( false );
        this.MaxCombo.setEnabled( false );
        this.CentralPanel.setVisible( false );
        this.findBtn.setEnabled( false );
        this.mingapLabel.setEnabled( false );
        this.maxgapLabel.setEnabled( false );
        
        this.fileMenu.setEnabled( false );
        this.EditMenu.setEnabled( false );        
    }
    
    private void enableAll(){
        this.ScheduleBtn.setEnabled( true );
        this.minCombo.setEnabled( true );
        this.MaxCombo.setEnabled( true );
        this.CentralPanel.setVisible( true );
        this.findBtn.setEnabled( true );
        this.mingapLabel.setEnabled( true );
        this.maxgapLabel.setEnabled( true );
        
        this.fileMenu.setEnabled( true );
        this.EditMenu.setEnabled( true );        
    }
    
    private void initializeFormView(){
        this.FormViewTab = new javax.swing.JTabbedPane();
        
        this.grpPanel = new GroupPanel();
        this.ExamCentrePanel = new ExamCentrePanel();
        this.prgPanel = new ProgramPanel();
        this.formViewCourses = new CoursePanel();
        
        this.FormViewTab.add( "Group", this.grpPanel );
        this.FormViewTab.add( "Course", this.formViewCourses );
        this.FormViewTab.add( "Centre", this.ExamCentrePanel );
        this.FormViewTab.add( "Program", this.prgPanel );
        
        this.FormViewTab.addChangeListener( new javax.swing.event.ChangeListener() {
            public void stateChanged(ChangeEvent e) {
                if(DEBUG)
                    System.out.println( "state changed" );
                if( FormViewTab.getSelectedComponent() == formViewCourses ){
                    if(DEBUG)
                        System.out.println( "form view" );
                    initializeCoursePanel();
                }
                else
                    if( FormViewTab.getSelectedComponent() == prgPanel ){
                        controller.reRead();
                        prgPanel.update();
                        if(DEBUG)
                            System.out.println("System is re reading");
                    }
            }
        });
    }
    
    private void makeRemoteSchedule( boolean onCancel ){
        if( ! this.remoteSchedulingCheck.isSelected() )    {
            this.remoteSchedulingEditMenu.setEnabled( false );
            return;    
        }
        this.remoteScheduleForm.setVisible( true );
        if( this.remoteScheduleForm.getReturnStatus() == this.remoteScheduleForm.RET_OK ){
            this.controller.setRemoteSchedulerIP( this.remoteScheduleForm.getIP() );
            this.controller.setRemoteSchedulerPort( this.remoteScheduleForm.getPortNo() );
            this.remoteSchedulingEditMenu.setEnabled( true );
        }
        else{
            if( onCancel )
                this.remoteSchedulingCheck.setSelected( false );
        }
    }
    
    private SwingWorker<Result, Void> getSchedulerThread(){
        return new SwingWorker<Result, Void>(){        
        
            @Override
        public Result doInBackground(){                
            controller.reRead();            
            Result rs = controller.start( remoteSchedulingCheck.isSelected() );                        
            return rs;
        }   
            
            @Override
        public void done(){                
        try{
            Result state = this.get();
            monitor.setVisible( false );            
            
            if( onSystemError() )return;
            
            if( state.executedSuccessfully() ){                            
                onSuccessfullScheduling( state );                                
            }
            else
                JOptionPane.showMessageDialog( null, state.getError(), "Error", JOptionPane.ERROR_MESSAGE );
        }
        catch( Exception e ){                    
            System.out.println( "error in done "+e.getMessage() );
        }
        }
        };        
    }
    
    private boolean onSystemError() {
        if (SystemError) {
            this.dispose();
            return true;
        }
        return false;
    }
    
    public void notify( SystemStepState state ){
        if( this.DEBUG )System.out.println("notified...");
        this.monitor.display_state(state);
    }
    
    /**
     * This method returns if the scheduling task is being cancelled by user.
     * 
     * @return true if cancelled else false
     */
    public boolean isCancelled(){
        return this.userCancelled;
    }
    
    public boolean isPaused(){
        return false;
    }
    
    public void cancel(){
        this.userCancelled = true;
    }
    
    /**
     * This method is called when the system resources is taken up completly and system is unable to continue
     * So, instead of simply ending abruplty, This func will degrade gracefully
     */
    public void degradeGracefully( ){
        this.SystemError = true;
        this.userCancelled = true;        
    }
            
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AboutBtn;
    private javax.swing.JPanel CentralPanel;
    private javax.swing.JPanel CentrePanel;
    private javax.swing.JPanel CentreTreePanel;
    private javax.swing.JPanel DataTreePanel;
    private javax.swing.JPanel DisplayPanel;
    private javax.swing.JMenu EditMenu;
    private javax.swing.JPanel ForeGroundPanel;
    private javax.swing.JRadioButton FormVewBtn;
    private javax.swing.JRadioButtonMenuItem FormView;
    private javax.swing.JPanel InputPanel;
    private javax.swing.JComboBox MaxCombo;
    private javax.swing.JMenu MiscellneousMenu;
    private javax.swing.JPanel NorthPanel;
    private javax.swing.JButton ScheduleBtn;
    private javax.swing.JTabbedPane TreeTab;
    private javax.swing.JRadioButtonMenuItem TreeView;
    private javax.swing.JRadioButton TreeViewCombo;
    private javax.swing.JMenu ViewMenu;
    private javax.swing.JTabbedPane centralTab;
    private javax.swing.JPanel coursePanel;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JButton findBtn;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel maxgapLabel;
    private javax.swing.JComboBox minCombo;
    private javax.swing.JLabel mingapLabel;
    private javax.swing.JCheckBoxMenuItem remoteSchedulingCheck;
    private javax.swing.JMenuItem remoteSchedulingEditMenu;
    // End of variables declaration//GEN-END:variables
    private ExamDataTree DataTree = null;
    private java.awt.Image URGLogo = null;
    private About Dialog = null;
    private Database DatabaseSettings = null;
    private Controller controller = null;
    private puexamroutine.control.database.DatabaseWriter writer = null;
    private ExamRoutineTree RoutineTree = null;
    private ExamCentreTree CenterTree = null;    
    private SchedulingProgressMonitor monitor = new SchedulingProgressMonitor( null, this );    
    private boolean userCancelled;
    private boolean SystemError=false;        
    private RemoteScheduleLocationIndentifierForm remoteScheduleForm = new RemoteScheduleLocationIndentifierForm( null );
    private CoursePanel courses = new CoursePanel();
    
    // form view components
    private javax.swing.JTabbedPane FormViewTab;
    private GroupPanel grpPanel;
    private ExamCentrePanel ExamCentrePanel = null;
    private ProgramPanel prgPanel = null;
    private CoursePanel formViewCourses = null;
}