
//                              !! RAM !!

package puexamroutine.ui;

import puexamroutine.control.Controller;
import puexamroutine.control.database.DatabaseWriter;
import puexamroutine.control.domain.list.ProgramList;
import puexamroutine.control.domain.Group;
import puexamroutine.control.domain.Program;
import puexamroutine.control.domain.College;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import puexamroutine.ui.form.CollegesForm;
import puexamroutine.ui.form.updateProgramForm;
import puexamroutine.ui.form.ProgramGroupInputForm;

/**
 *
 * @author  Sumit Shresth
 */
public class ProgramPanel extends javax.swing.JPanel {

    /** Creates new form ProgramPanel */
    public ProgramPanel() {
        initComponents();
        this.model = (DefaultTableModel) this.prgTable.getModel();
    }

    public void update() {
        this.writer = this.controller.getDatabaseManager();
        this.centres = this.writer.getCentres().keySet().toArray(new String[]{});
        this.initialize(this.controller.getGroupList().getGroupAndPrograms());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        prgTable = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        jButton1.setText("ADD");
        jButton1.setToolTipText("add new Program");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);

        jButton2.setText("DEL");
        jButton2.setToolTipText("delete selected Program");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);

        jButton3.setText("UPDATE GROUP");
        jButton3.setToolTipText("update selected program's group");
        jButton3.setEnabled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);

        jButton4.setText("UPDATE PROGRAM");
        jButton4.setToolTipText("update selected program");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);

        jButton5.setText("UPDATE COLLGES");
        jButton5.setToolTipText("update selected  program's colleges");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        prgTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Group", "Program", "Colleges"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        prgTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(prgTable);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
    this.updateProgramColleges();    
}//GEN-LAST:event_jButton5ActionPerformed

private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
    this.updateProgram();
}//GEN-LAST:event_jButton4ActionPerformed

private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    this.updateGroup();
}//GEN-LAST:event_jButton3ActionPerformed

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    this.addProgram();
}//GEN-LAST:event_jButton1ActionPerformed

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    this.deleteProgram();
}//GEN-LAST:event_jButton2ActionPerformed

    public void initialize( Controller cont ){
        this.controller = cont;
        update();
    }
    
    private void initialize( java.util.HashMap<Group, ProgramList > list ){
        while( model.getRowCount() > 0 ){
            this.model.removeRow( 0 );
        }
        
        java.util.Iterator<Group> grpItr = list.keySet().iterator();
        while( grpItr.hasNext() ){
            Group grp = grpItr.next();
            java.util.Iterator<Program> prgItr = list.get(grp).getPrograms().iterator();
            while( prgItr.hasNext() ){
                Program prg = prgItr.next();
                ProgramColleges colls = new ProgramColleges(prg);
                colls.addColleges( prg.getSupportingColleges() );
                this.model.addRow( new Object[]{ grp, prg, colls } );
            }
        }
    }
    
    private void updateProgramColleges(){
        final int row = this.prgTable.getSelectedRow();
        if( row == -1 ){
            JOptionPane.showMessageDialog( null, "Please Select Program/Row from Table", "Program Not Selected", JOptionPane.ERROR_MESSAGE );            
            return;
        }
        
        ProgramColleges colls = (ProgramColleges) this.model.getValueAt( row, 2 );
        Program prg = colls.getProgram();
        Group grp = prg.getGroup();
        try{
            grp = this.controller.getGroupList().getGroup( grp.getFaculty(), grp.getLevel(), grp.getDiscipline() );
        }
        catch( Exception e ){
            System.out.println( "Proper Group could not be obtained" );
        }
        CollegesForm form = new CollegesForm( null, prg, this.centres, this.controller.getGroupList().getCoursesMap( grp ) );
        form.setVisible( true );
        if( form.getReturnStatus() == form.RET_OK ){
            java.util.Iterator<College> prgColls = colls.getProgramColleges().iterator();
            while( prgColls.hasNext() ){
                College c = prgColls.next();
                boolean st = this.writer.removeCollegeProgram( c.getCollegeName(), prg.getProgramName() );
                if( ! st ){
                    JOptionPane.showMessageDialog( null, c.getCollegeName()+" could not be removed", "Error while updating", JOptionPane.ERROR_MESSAGE );
                }
            }            
            Program newProgram = form.getProgram( grp );
            ProgramColleges newPrgColls = new ProgramColleges(newProgram);
            newPrgColls.addColleges( newProgram.getSupportingColleges() );
            boolean st = this.controller.addProgramColleges(newProgram);
            if( st )
                this.model.setValueAt( newPrgColls, row, 2  );            
            else{
                JOptionPane.showMessageDialog( null, "The program could not be updated", "Program Update Error", JOptionPane.ERROR_MESSAGE );
            }
        }
    }
    
    private void updateProgram(){
        final int row = this.prgTable.getSelectedRow();
        if( row == -1 ){
            JOptionPane.showMessageDialog( null, "Please Select Program/Row from Table", "Program Not Selected", JOptionPane.ERROR_MESSAGE );            
            return;
        }
        
        final Program prg = (Program) this.model.getValueAt( row, 1 );
        
        final String fac = prg.getGroup().getFaculty();
        final String level = prg.getGroup().getLevel();
        final String discp = prg.getGroup().getDiscipline();
        
        updateProgramForm form = new updateProgramForm( null, fac, level, discp, prg.getProgramName() );
        form.setVisible( true );
        if( form.getReturnStatus() == form.RET_OK ){
            if( this.writer.updateProgram( prg.getProgramName(), fac, level, discp, form.getText() )){
                boolean st = prg.rename( form.getText() );
                if( ! st ){
                    JOptionPane.showMessageDialog( null, "The program Name could not be updated", "Program Update Error", JOptionPane.ERROR_MESSAGE );
                }
                final Program prg1 = ((ProgramColleges) this.model.getValueAt( row, 2 )).getProgram();
                st = prg1.rename( form.getText() );
                if( ! st ){
                    JOptionPane.showMessageDialog( null, "The program Name could not be updated", "Program Update Error", JOptionPane.ERROR_MESSAGE );
                }
            }
            else
                JOptionPane.showMessageDialog( null, prg+" cannot be updated", "update Program error", JOptionPane.ERROR_MESSAGE );
        }
    }
    
    private void updateGroup(){
        final int row = this.prgTable.getSelectedRow();
        if( row == -1 ){
            JOptionPane.showMessageDialog( null, "Please Select Program/Row from Table", "Program Not Selected", JOptionPane.ERROR_MESSAGE );            
            return;
        }        
        final Program prg = (Program) this.model.getValueAt( row, 1 );        
        java.util.Collection<Group> grps = this.controller.getGroupList().getGroups();
        ProgramGroupInputForm form = new ProgramGroupInputForm( null, prg, grps );
        form.setVisible( true );
        if( form.getReturnStatus() == form.RET_OK ){
            Group selectGrp = form.getGroup();
            boolean st = this.writer.updateProgramGroup( prg.getProgramName(), selectGrp.getFaculty(), selectGrp.getLevel(), selectGrp.getDiscipline() );
            if( ! st ){
                JOptionPane.showMessageDialog( null, prg.getProgramName()+" could not be updated", "Program Not Updated", JOptionPane.ERROR_MESSAGE );
            }
            else{
                this.model.setValueAt( selectGrp, row, 0 );
                ((Program)this.model.getValueAt(row, 1 )).setGroup(selectGrp);
                ((ProgramColleges)this.model.getValueAt(row, 2 )).getProgram().setGroup(selectGrp);
            }
        }
    }
    
    private void addProgram(){
        ProgramGroupInputForm form = new ProgramGroupInputForm( null, null, this.controller.getGroupList().getGroups() );
        form.setVisible( true );
        if( form.getReturnStatus() == form.RET_OK ){
            Group grp = form.getGroup();
            String prg = form.getProgramName();
            Program newProg = new Program( prg, grp );
            CollegesForm collform = new CollegesForm( null, newProg, this.centres, this.controller.getGroupList().getCoursesMap( grp ) );
            collform.setVisible( true );
            if( collform.getReturnStatus() == collform.RET_OK ){
                newProg = collform.getProgram(grp);
                boolean st = this.controller.addProgram(newProg);
                if( st ){
                    this.model.addRow( new Object[]{ grp, newProg, new ProgramColleges(newProg, newProg.getSupportingColleges() ) } );
                }
                else{
                    JOptionPane.showMessageDialog( null, "Program "+newProg.getProgramName()+" could not be added in database.", "Error Progarm Addition", JOptionPane.ERROR_MESSAGE );
                }
            }        
        }
    }
    
    private void deleteProgram(){
        final int row = this.prgTable.getSelectedRow();
        if( row == -1 ){
            JOptionPane.showMessageDialog( null, "Please Select Program/Row from Table", "Program Not Selected", JOptionPane.ERROR_MESSAGE );            
            return;
        }
        final Program prg = (Program) this.model.getValueAt( row, 1 );
        final Group grp = prg.getGroup();
        int op = JOptionPane.showConfirmDialog( null, "Are you sure you want to delete Program "+prg.getProgramName()+"?", "Program Deletion Confirmation",JOptionPane.YES_NO_OPTION );
        if( op == JOptionPane.NO_OPTION ){
            return;
        }
        boolean st = this.writer.removeProgram( prg.getProgramName(), grp.getFaculty(), grp.getLevel(), grp.getDiscipline() );
        if( st ){
            this.model.removeRow(row);
        }
        else{
            JOptionPane.showMessageDialog( null, "Program "+ prg.getProgramName()+" could not be deleted from database.", "Error Progarm Deletion", JOptionPane.ERROR_MESSAGE );
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable prgTable;
    // End of variables declaration//GEN-END:variables

    private Controller controller = null;
    private DatabaseWriter writer = null;
    
    private String[] centres;
    private DefaultTableModel model = null;
    
    /**
     * This class represents the colleges of a particular program.
     * 
     * @author Sumit Shresth
     */
    class ProgramColleges implements java.io.Serializable{
        
        public ProgramColleges( Program prg ){
            this.prg = prg;
        }
        
        public ProgramColleges( Program prg, java.util.Collection<College> coll ){
            this( prg );
            this.addColleges(coll);
        }
        
        public void addColleges( java.util.Collection<College> coll ){
            this.PrgColleges.addAll(coll);
        }
        
        public void addCollege( College coll ){
            this.PrgColleges.add(coll);
        }
        
        @Override
        public final String toString(){
            java.util.Iterator<College> collItr = this.PrgColleges.iterator();
            String ret = "";
            while( collItr.hasNext() ){
                ret += collItr.next().getCollegeName() + ",";
            }
            ret = ret.substring( 0, ret.length() - 1 );
            return ret;
        }
        
        public final java.util.Collection<College> getProgramColleges(){
            return this.PrgColleges;
        }
        
        public final Program getProgram(){
            return this.prg;
        }
        
        private final Program prg;
        java.util.Collection<College> PrgColleges = new java.util.ArrayList<College>();
    }
    
}